### ISSUE TITLE
VC's have too much access to visit reports

### ISSUE THREAD

**Issue by jessicamorris64** [cssat/sprout-issues#100]
this is occurring in production
**Describe the bug**
Visit Coordinators due to a bug are currently able to do the following:
- Add Reports to a Referral
- Delete Reports on a Referral
- Move reports from on Referral to another Referral, this could even be in a different case
- They can see reports that are in Review & Resume status
- Info tiles display telling them #’s of reports that need to be reviewed and finalized
- They can only see reports in their Organization
- Reopen resolved referrals

**To Reproduce**
1. log in as a VC
2. go to a referral with reports
3. VC's can do all the items listed in the bug when the referral is assigned to providers within their organization.

1. Go to a resolved referral and reopen it. (this should also not happen)

**Expected behavior**
Visit Coordinators should NOT be able to edit Visit Reports in anyway possible.
VC's should be able to ONLY VIEW reports after they have been approved and finalized.
VC's should be able to see approved reports for all providers not just the ones in their organization.

- VC's should not be able to reopen resolved referrals.

**Screenshots**

**Desktop (please complete the following information):**
 - Browser chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by joemienko** [comment]
@jessicamorris64 - We discussed this in our morning triage meeting. From the email thread, it sounds like there is also a desire to lock down VC permissions more generally (i.e. ability to edit referrals after assignment, etc.) (see #95)

We were thinking that it would make sense to have @Deanna1968 take a look at the table of roles and permissions here: https://docs.google.com/document/d/1c-FkR4ofWJ8qrs4bAxWKQjHItJ5It4c6EyRFZaOrguU/edit?usp=sharing

This table was generated late last year, but I believe is still current. 

Based on Deanna's guidance, we can embark on a project to more completely revamp the VC permission model. 

We can discuss more at 2!

-Joe

**Comment by joemienko** [comment]
- @sarahyatsko @jessicamorris64 @Deanna1968 will meet to discuss this required permissions for VCs 
- @cssatmcfunk will work to get the report epic completed by next week. Wednesday would be ideal.

**Comment by joemienko** [comment]
@Deanna1968  - As per Ronda Haun, this is no longer an issue. VCs havee access to all information in their current roles at DCYF. 

Can we close this?

**Comment by Deanna1968** [comment]
close

**Comment by jessicamorris64** [comment]
You Have a New State of Washington Secure Email Portal Message 

"Morris, Jessica (DCYF)" <jessica.morris@dcyf.wa.gov> has sent you an encrypted message via State of Washington Secure Email Portal.

   Subject: Re: [cssat/sprout-issues] VC's have too much access to Visit Reports (#100)
   Sent: June 16, 2020 3:17:47 PM, PDT

ACTIVATION INFORMATION:

The State of Washington Secure Email Portal has changed providers. You will need to create a new account to access your message. We apologize for the inconvenience. Once you've created your account, you can view your messages you receive from "Morris, Jessica (DCYF)" <jessica.morris@dcyf.wa.gov> directly from your State of Washington Secure Email Portal account:

   Email: reply@reply.github.com
   MESSAGE EXPIRY: July 16, 2020 3:18:21 PM, PDT
   You have 30 day(s) left to collect this message before it expires. Once the message
 expires, it will be permanently removed from the server.
   Click here to create your account and read your message: https://emailencryption.twsegcloud.com/login.html?msgUserId=141e0068af4735b8&enterprise=trustwave_watech&rrRegcode=X9t7nMG7&locale=en_US

NEED HELP?

Need help? Visit the State of Washington Secure Email Portal https://emailencryption.twsegcloud.com/branding/trustwave_watech/en_US/help/index.html

**Comment by joemienko** [comment]
Hi all, 

Responding to Jessy's autosecured email (which did not need to be secure) - we should confirm that VCs are not able to make edits to visit reports (or delete them). 

@sarahyatsko  - Can you easily confirm this from your audit of permissions?

**Comment by sarahyatsko** [comment]
Yep!

**Comment by Deanna1968** [comment]
Hi Joe,
VCs should not be able to edit the visit reports nor delete them!

deanna

**Comment by joemienko** [comment]
@sarahyatsko has agreed to close this issue, and split it into 1-2 separate issues related to VC ability to edit/delete referrals
