### ISSUE TITLE
Resolved referrals have old reports that have not been approved, are not included in reports

### ISSUE THREAD

**Issue by jessicamorris64** [cssat/sprout-issues#101]
**Is your feature request related to a problem? Please describe.**
There are quite a few resolved referrals that have reports that are in the resume or finalize status.  Making them not displaying for our staff and would skew the data on number of reports and reports not attended.  Additionally, these in progress reports are not visible to our social workers, public disclosure and discovery staff, that is built by design…. 
However, the fact that they are old and on resolved referrals is concerning.  We need providers to complete their work or this is going to provide inaccurate information. this appears to be a common issue for No Show visits. 

**Describe the solution you'd like**
Can reminders/ticklers be set up for visit approvers, possible reporting from OIAA. the team may need to brainstorm other possible solutions to prevent old reports that have not been approved from sitting on resolved referrals for an extended period of time.

**Describe alternatives you've considered**

**Additional context**

**Prioritization Process**

- [ ] Confirm the issue is a feature to which we want to devote resources. 

- [ ] Write user story in `as a (role) I want (something) so that (benefit)` format. 

- [ ] Label story Large, Uncertain, Small. If the story is too large, convert the story to a milestone/epic. 

- [ ] Label story as an [active backlog](https://github.com/cssat/sprout-issues/projects/1) issue (i.e. an issue on which we will be actively working).

- [ ] Prioritize the story relative to other items in the [active backlog](https://github.com/cssat/sprout-issues/projects/1).

- [ ] Review progress/priorities in weekly collaboration meeting.

**Comment by joemienko** [comment]
- Thoughts from @sarahyatsko are to propose a cleanup of resolved referrals after the filter list epic is deployed
- Also, explore this as a provider report needed "to do your job" (@joemienko  to follow up with Barb G.)
- Could potentially reveal unapproved report counts to social workers

**Comment by joemienko** [comment]
As of today, CSSAT's best thoughts on this are to run a report to providers that helps them do cleanup per @sarahyatsko's comments. 

As a first pass at this, however, we ought to see how well the features available under the referral list epic help providers do this cleanup (without ad hoc reporting requirements)

**Comment by joemienko** [comment]
Adding this to ToDo column with a provisional assignment to @sarahyatsko . 

Also flagging as blocked due to the current plan for resolution (i.e. having @sarahyatsko train users to make use of the filters to clean up report litter)
