### ISSUE TITLE
Visit report location is preventing reports from being saved 

### ISSUE THREAD

**Issue by sarahyatsko** [cssat/sprout-issues#103]
**Describe the bug**
If the Visit Location in the Visit Report does not have an address, the Service Admin or Org Admin at a provider agency is unable to approve a visit report.  The visit location field is auto-populated with information from the referral  and this is often incomplete, creating an error message for the Basic User. However, the Basic User can submit the report to their supervisor, but the supervisor can not approve the visit report unless this Visit Location field contains some text. 

The work around has been to put something, anything, in the address field. However, that’s doesn’t seem to be working for some referrals at the moment.  See screen shot for case number 1973868. 
<img width="737" alt="Screen Shot 2020-05-06 at 3 11 21 PM" src="https://user-images.githubusercontent.com/49733235/81233630-e60cce80-8fab-11ea-88f0-68061ad4e631.png">
 The visit report for May 4 populated the visit location as “Counseling Connections NW in Lakewood through zoom” which is pinked out, preventing the supervisor at the agency from approving and submitting the report to DCYF. 

**To Reproduce**
1. Find a newly ingested referral - might need to be one where Social Worker has indicated in FamLink that the visit should be virtual. 
2. Click on Reports and Add a Report. 
3. Scroll down to Visit Location
4. See that toggle boxes behaving badly - Other is listed, but can't be chosen, and no address can be added to the other options. 

**Expected behavior**
Sprout should let you add an address - even a fake one. 

**Screenshots**
Attached

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sarahyatsko** [comment]
Immediate concern on this referral has been addressed.  Sarah will look to combine this issue with another similar one and close this out.

**Comment by subaykan** [comment]
dup
