### ISSUE TITLE
Maintenance page should not be displayed in error conditions.

### ISSUE THREAD

**Issue by sarahyatsko** [cssat/sprout-issues#104]
**Describe the bug**
When user in a routing organization attempts to download a billing file, they are taken to a confusing error page. 

**To Reproduce**
1. Log on to a VC org
2. Go to My Organization
3. Click on DOWNLOAD button and enter dates
4. See error page

**Expected behavior**
An error page that says something like, "you have tried to perform a task that you do not have the proper permission to perform, or that can not be performed based on the organization you are a member of"

**Screenshots**
<img width="992" alt="Screen Shot 2020-05-11 at 4 25 44 PM" src="https://user-images.githubusercontent.com/49733235/81622030-cf4bea80-93a4-11ea-8e57-17b557413b67.png">

**Comment by joemienko** [comment]
This issue could reasonably be split into three: 

-- Ideal state is that the download button is not even available to VC organizations. (see #109 )
-- Maintenance page should not be displayed in error conditions. (address within this issue)
-- Maintenance page should be updated to reflect current sprout branding and ownership. (see #111 )

**Comment by sarahyatsko** [comment]
Sarah will split this in to 3 issues and close this one.

**Comment by joemienko** [comment]
Closed accidentally
