### ISSUE TITLE
DCYF's Parkland office not on dropdown list of offices on visit report

### ISSUE THREAD

**Issue by sarahyatsko** [cssat/sprout-issues#106]
**Describe the bug**
On the visit report is a field to enter the name of the referring Social Worker and what office they work in.  There was an office added after Sprout launch called "Parkland Satellite" and it is not in the drop down list ofDCYF offices to chose in the Visit Report. 

**To Reproduce**
Open a new visit report
Scroll down to Social Worker
Click on drop down list for DCYF office.  List of office names appear.  List does not contain Parkland. 

**Screenshots**
<img width="1176" alt="Screen Shot 2020-05-30 at 12 27 20 PM" src="https://user-images.githubusercontent.com/49733235/83337590-b0d56280-a271-11ea-87e0-436943cf92cb.png">

Related issue:
Visit Report does not auto populate with social worker's DCYF office. Visit supervisor must click on the drop down list and fill this in each time they create a visit report.

**Comment by sarahyatsko** [comment]
Marshal and Sarah discussed this and agreed that adding Parkland office should not be difficult and Ari could give that a go.  Sarah will also add another Issue to the backlog to completely clean this list - or eliminate the need for it.

**Comment by sarahyatsko** [comment]
In late March 2021 another new office was added called "Vancouver - Clark" This should also be added to this list of offices on the visit report

**Comment by subaykan** [comment]
ready to deploy

**Comment by subaykan** [comment]
dup
