### ISSUE TITLE
The rebrand banner is no longer needed. 

### ISSUE THREAD

**Issue by ariadnaeleni** [cssat/sprout-issues#107]
Our users are well aware that Oliver has rebranded to Sprout, and the banner on the login page is no longer necessary

**Comment by joemienko** [comment]
@Deanna1968  - do you agree with this?

**Comment by Deanna1968** [comment]
Hi Joe, 
I agree its not needed!

**Comment by joemienko** [comment]
@ariadnaeleni  - please see the note above. Unless @yhtill feels otherwise, you should feel free to roll this into the sub-branch you are working on.

**Comment by joemienko** [comment]
Removed!
