### ISSUE TITLE
Download button is unnecessary and confusing for VCs

### ISSUE THREAD

**Issue by sarahyatsko** [cssat/sprout-issues#109]
**Is your feature request related to a problem? Please describe.**

The download button on the My Organization page allows Org Admin users to download an Excel file with Intake and Visit Report data for a particular date range.  Given that no one in a VC organization would be performing either Intake or completing visit reports, the download button is unnecessary and confusing for these users.  

**Describe the solution you'd like**
Remove the Download button for VC orgs.

**Comment by subaykan** [comment]
Download button now serves the dashboard-service generated excel for VC's providers' data
