### ISSUE TITLE
The Sprout maintenance page has an expired SSL cert

### ISSUE THREAD

**Issue by yhtill** [cssat/sprout-issues#110]
The SSL certificate for the Sprout maintenance page appears to have expired, so when the maintenance page is put up, users see a security warning page instead of the maintenance page.

**Comment by lucypotato** [comment]
Updated the SSL certificate in AWS CloudFront so now the maintenance page is up again: https://maintenance.oliverservices.org/

**Comment by lucypotato** [comment]
Also set up the new sproutservices domain too: https://maintenance.sproutservices.org/
