### ISSUE TITLE
The Sprout maintenance page has outdated branding and ownership

### ISSUE THREAD

**Issue by joemienko** [cssat/sprout-issues#111]
Breaking off from #104

**Comment by subaykan** [comment]
low pri, easy fix

**Comment by lucypotato** [comment]
Updated the maintenance page to match Sprout's background colors, footer, and logo: https://maintenance.sproutservices.org/

![image](https://github.com/cssat/sprout-issues/assets/13345485/70130edd-b1c9-4308-ab60-2dcdff4b004d)
