### ISSUE TITLE
A Visit Supervisor Can Not Enter a Transport that Happens Mid-Visit

### ISSUE THREAD

**Issue by sarahyatsko** [cssat/sprout-issues#115]
**Is your feature request related to a problem? Please describe.**
It happens that during a lengthy visit, the location may change and there is a mid-visit transport.  Per one provider this is not that rare. 

_"This is typically going to happen more during the summer, during the morning visits the parents might start off inside, and then move to another outdoor location once it warms up. Or they start somewhere to grab a bite to eat and then move somewhere to play outside."_

Sprout allows multiple to and multiple from transport legs, but once the visit starts, it is not possible to stop the visit, add a transport mid visit and then re-start the visit time. 

**Describe the solution you'd like**
Addable for Visit start and end times???

**Describe alternatives you've considered**
Having the provider enter as two visits. 
Adding the transport as an additional "To" leg - although this makes the timing wonky. 

**Prioritization Process**

- [ ] Confirm the issue is a feature to which we want to devote resources. 

- [ ] Write user story in `as a (role) I want (something) so that (benefit)` format. 

- [ ] Label story Large, Uncertain, Small. If the story is too large, convert the story to a milestone/epic. 

- [ ] Label story as an [active backlog](https://github.com/cssat/sprout-issues/projects/1) issue (i.e. an issue on which we will be actively working).

- [ ] Prioritize the story relative to other items in the [active backlog](https://github.com/cssat/sprout-issues/projects/1).

- [ ] Review progress/priorities in weekly collaboration meeting.

**Comment by subaykan** [comment]
Proposed solution to explore:
In addition to the "To Visit" and "From Visit" options, we can add a third type of transport leg that we can call "During Visit" or something similar.
The billing code could then allow time overlaps of "During Visit" transport legs with the Visit Time so there is no conflict.

**Comment by subaykan** [comment]
Note: I think we would need to launch the billing code first or coordinate the launch of the UI change so there is no time where the clash would happen.

Also: this would need to be reflected in the visit report form, summary views, and also download document version. We need to make sure we make changes to add the "during visit" transport legs anywhere where the other ones are shown

**Comment by keithligon** [comment]
Having a visit time addable would allow the visit time time and transport time to be tracked separately.  Would still need changes previously called out to form, validation, summary, download, etc.  Is there any need for multi-date visits, overnights?  This could support that as well.

![visit-times](https://github.com/cssat/sprout-issues/assets/81592046/dfc05073-d46f-4a61-89ed-8cc537e7826a)

**Comment by subaykan** [comment]
This (addable visit time) could be a way to solve visits that are multi day.  In this case, we don't need to track visit and transport time separately (more than we already do currently). We need to have a transport time that can exist within the visit time boundaries and not cause a conflict. I think the straightforward solution to this problem would be to add an "In Visit" or "During Visit" type of transport details element. We can discuss, I'm open to ideas. 

Making visit time addable is a larger scope of data model change compared to this approach. We can evaluate.

**Comment by tinhart** [comment]
Can we close this ticket since we launched the mid-visit transport functionality in July?

**Comment by sarahyatsko** [comment]
Is this a ticket? Or an issue in GitHub? 

If it’s an issue in GitHub, yes.  And if it’s a ticket, as long as it’s answered, yes. 

Sarah Yatsko
Director
Center for Social Sector Analytics & Technology (CSSAT)
University of Washington School of Social Work
Box 354900 |  Seattle, WA 98105
Cell 206.841.2821 / ***@***.***

**Comment by tinhart** [comment]
I'll go ahead and close the issue since the work is complete and the feature deployed.
