### ISSUE TITLE
Users can return to a cached rendering of PII after they have logged off

### ISSUE THREAD

**Issue by joemienko** [cssat/sprout-issues#120]
**Describe the bug**
In certain scenarios, users can return to a cached rendering of PII after they have logged off from Sprout. 

**To Reproduce**
Steps to reproduce the behavior (will only work with a sufficient level of browser cache):
1. Go to http://sproutservices.org (note: not https)
2. Log in
3. Log out
4. Type google.com directly into the browser
5. Hit the back button

**Expected behavior**
Sprout asks web browsers to not store cache, and thus we should not see a cached rendering of the referral list. 

**Additional context**
Only appears to be occurring in Chrome. 

**Diagnosis**
Sprout currently does (and always has) attempt to prevent the local caching of information by browsers. This is accomplished through the inclusion of headers which browsers should take as an instruction to not store information. Cache, however, is not a precisely defined term. In order to improve user experience, browsers may store browser cache directly in a local file system, but may also store session information in places/ways that are not precisely interpreted as cache (e.g. directly on the [GPU](https://www.chromium.org/developers/design-documents/gpu-accelerated-compositing-in-chrome)). Chrome appears to be interpreting our current headers in such a way that information (regardless of whether or not it is classically defined as cache) is accumulating in users' local environments.  

**Solution**
Replace current headers with more opinionated headers regarding the storage of cache.

**Comment by joemienko** [comment]
**Issue resolved as a part of the following deployment**

```
RELEASE NOTES:
## Release 08/28/2020 23:32
* Enable substituting a view for a table in sequelize queries;
* Add Cache-Control: no-store header to cache disabling middleware.
* Post production 20200802205950 deploy
```

NOTE - Users who were experiencing this bug will likely need to [clear their cache](https://support.google.com/accounts/answer/32050?co=GENIE.Platform%3DDesktop&hl=en) prior to verifying that this solution has "worked".

**Comment by jessicamorris64** [comment]
we are seeing that the browser may still be storing cache information for sprout. this is a security concern. currently if you close the window but not the entire browser sprout does not require you to log in again. the requirement is that  no matter the browser, if the tab/window sprout is being viewed in is closed, then the page is reopened, it will require you to log in again, even if you did not close the entire browser window and only closed the tab. if sprout is not active in any of the open tabs in the browser then it should make sure you are logged out and will require a new log in if the sprout webpage is opened again.
