### ISSUE TITLE
‘Select’ watermark vale does not disappear once a value is entered (shadow select)   [CANS-F]

### ISSUE THREAD

**Issue by cdoran99** [cssat/sprout-issues#123]
Select reason for referral and move off Face Sheet and come back. Select reappears beside value.  Doesn’t matter which value you select. This makes it appear that you haven’t selected a value even though you have.
This seems to occur any place in CANS-F the ‘Select’ value/watermark is located including the Target plan for change, Primary Reason for Service Referral, End of intervention, etc.

**Comment by sarahyatsko** [comment]
Reviewed with Taku and accepted
