### ISSUE TITLE
Error messaging not helpful [CANS-F]

### ISSUE THREAD

**Issue by cdoran99** [cssat/sprout-issues#136]
There is no way to tell what’s missing when you get an   error message before saving.   E.g. cant complete before the intervention

**Comment by yhtill** [comment]
Everything that's currently required is marked as missing on attempting to save/leave the CANS form.

**Comment by cdoran99** [comment]
Need to review with group for desired flow and functionality

**Comment by subaykan** [comment]
will review for prioritization

**Comment by subaykan** [comment]
note: it is possible to identify required fields that need to be addressed, fields are highlighted in pink/red color
