### ISSUE TITLE
Comment font size on report [CANS-F]

### ISSUE THREAD

**Issue by cdoran99** [cssat/sprout-issues#139]
When comments are made in the scoring sheet they are displayed on the report. However the font of the comments is so small most testers didn’t notice that the comments were included in the report.

**Comment by yhtill** [comment]
Is this what is being described as too small to notice, or am I either misunderstanding or not able to reproduce this bug?
![image](https://user-images.githubusercontent.com/20548990/105930921-295a1200-5fff-11eb-993e-50b0bf2a5815.png)

**Comment by nelsosd** [comment]
Personally I think the “I like turtles” is challenging to see and could be easily missed. When there is more than one line it is easier to see that it is there.

Shannon Nelson, MSW/IT Technology Trainer
Technology Services
253-380-5273<tel:253-380-5273>/ Shannon.nelson@dcyf.wa.gov<mailto:Shannon.nelson@dcyf.wa.gov>
[cid:image003.jpg@01D53D58.43DF9440]<http://www.dcyf.wa.gov/>

**Comment by yhtill** [comment]
OK, I upped the font in the comments to the same size as surrounding fonts.

**Comment by jessicamorris64** [comment]
i agree with shannon that the "i like turtles" is a little difficult to read but i think that is the spacing of the letters being so close together, when they are long vertical letters. it's up to Taku but i would put this as low priority, since they can increase screen resolution and zoom in if they wish (just my opinion).

**Comment by cdoran99** [comment]
Thank you for checking, 

It looks good to me.  I think the work was done to make the font size the same for the comment and the left side column. 

Taku Mineshita MSW | System of Care & Service Array Program Manager 
Division of Child Welfare Programs | Olympia HQ
Office 360-902-7928| Cell 360-999-3110
Pronouns: he/him/his
