### ISSUE TITLE
I guess you CAN take back what you said [CANS-F]

### ISSUE THREAD

**Issue by cdoran99** [cssat/sprout-issues#146]
Assessment
After text has been entered into red comments filled, and assessments marked as completed, I can still go back and edit/remove comments so the field is blank. But it still shows as completed….
![image](https://user-images.githubusercontent.com/57012812/103431507-c1daaf00-4b85-11eb-8445-4a386c4a93ac.png)

**Comment by subaykan** [comment]
Check to see if still an issue

**Comment by chrishughes20** [comment]
Observed as fixed.
