### ISSUE TITLE
What is the availability of providers throughout the state?

### ISSUE THREAD

**Issue by joemienko** [cssat/sprout-issues#154]
For both CIHS and for Family Time, social workers, visit coordinators, and regional program staff want to know what providers are available for service at a given moment. 

This has been historically available in "provider finder". However, this tool is buggy and has not been prioritized at this time. 

Availability data can be recorded in various locations within Sprout.

A regular report of availability for providers would prevent the need for the development of desktop databases which is currently being contemplated as an alternative.

**Comment by subaykan** [comment]
Note: provider finder was deprecated and removed from Sprout.

**Comment by subaykan** [comment]
provider finder replacement not likely
