### ISSUE TITLE
What is the geographic distribution of visitation need?

### ISSUE THREAD

**Issue by joemienko** [cssat/sprout-issues#156]
Fiscal is interested in knowing how visitation requests are geographically distributed throughout the state. 

This information is (in principle) available in Sprout and could be run as a one-time or regular report to help Fiscal understand the geographic distribution of visitation requests.

**Comment by joemienko** [comment]
Note that this is presumably a need for other services as well - not just visitation.

**Comment by joemienko** [comment]
Per B. Gansberg - Until we have time for further development in geocoding and geospatial visualization, we are going to icebox this.

**Comment by subaykan** [comment]
DCYF will explore internally
