### ISSUE TITLE
Provider access to their own "raw" data

### ISSUE THREAD

**Issue by joemienko** [cssat/sprout-issues#158]
FIN and individual providers throughout the state have made repeated requests for access to curated extracts of data from Sprout to help them run various aspects of their business. 

The proposed model for providers is something along the lines of the FIN performance reports that were provided to FIN on a monthly basis prior to the implementation of the VC model throughout the state.

**Comment by subaykan** [comment]
Ongoing discussions toward evolution of the data download feature into a dashboard
