### ISSUE TITLE
Which providers have invoice anomalies? 

### ISSUE THREAD

**Issue by joemienko** [cssat/sprout-issues#161]
Fiscal is interested in a report that helps them flag anomalous billing activity from providers (e.g. extremely high mileage requests, activity fee reimbursements in excess of policy)

The development of flags on fiscal's monthly invoice reports has been requested to support this request. 

This should be for providers as well as fiscal. 

When the flags are triggered, there should be a color-coding scheme.

**Comment by joemienko** [comment]
We will fill this request, but we are going to wait on the color-coding until we have more specificity.

**Comment by subaykan** [comment]
Completed - Little Pink Boxes for you and me
