### ISSUE TITLE
DCYF users cannot download Visit Report history

### ISSUE THREAD

**Issue by yhtill** [cssat/sprout-issues#167]

**Comment by sarahyatsko** [comment]
@Deanna1968  I am documenting here that during our Tuesday 2 pm meeting on April 6th, Deanna provided an oral acceptance of this permission change and green lighted pushing this in to production.  - Sarah

**Comment by Deanna1968** [comment]
Correct!!

**Comment by subaykan** [comment]
Done. 

PR for this change https://github.com/cssat/sprout/pull/100

**Comment by cdoran99** [comment]
Reviewed and approved by Jessy on 01/28/2022
