### ISSUE TITLE
VC orgs will slow down 72 hour referrals

### ISSUE THREAD

**Issue by joemienko** [cssat/sprout-issues#172]
# Definitions 

72 hour visit organization - A family time organization, one per region, with contractual responsibilities to complete initial visits within 72 hours of DCYF receiving custody of a child. 

72 hour visit coordinator - A family time user, within a 72 hour visit organization, with org admin and region admin privileges. This user can view referrals, accept referrals, assign referrals, and approve visit reports. (All orgs appear to plan on having this role)

72 hour visit supervisor - A family time user, within a 72 hour visit organization, with basic user privileges. This user can view referrals, and submit visit reports.

Regular visit supervisor - A family time user, within a family time organization, with basic user privileges. This user can view referrals, and submit visit reports.

# User Story

As a 72 hour visit coordinator, I should receive 72 hour visit referrals for my region immediately after the family visit plan is approved in FamLink without the need for a visit coordinator, so that I can start work on 72 hour visit referrals without unnecessary delays. 

# Planned Solution

Update Sprout XML parsing and synthesize a new routing variable to route ingested referrals with a 72 hour reference value directly into a new queue of a 72 hour visit organization. 

See also #173 
See also #174 
See also #175 

# Working Implementation Timeline

1. Plan for code-completion 2-weeks after receipt of XML prototype, ideally week of July 12. **Requirement to start work - XML prototype(s) with new reference values.** 
2. Plan for feature acceptance by July 16. **Requirement to for acceptance testing - Test 72 hour referral push to Sprout UAT** 
3. Plan for provider training during week of July 19. **Requirement for training - Feature acceptance, feature deployment, and training referrals sent to usertest**

**Comment by joemienko** [comment]
Prerequisites for acceptance in UAT (each step to be documented for replication in production)

- [x] @yhtill Refresh the UAT database
- [x] @sarahyatsko add UAT 72-Hour VC Orgs with org admins, basic user, and region admin
- [x] @sarahyatsko add contracts for new UAT 72-Hour VC Orgs
- [x] @yhtill determine a replicable method for updating the routing tables on UAT
- [x] DCYF needs to push some referrals from FamLink UAT
- [x] @Deanna1968 to accept functionality (acceptance criteria forthcoming)

**Comment by joemienko** [comment]
Per @sarahyatsko `72 Hour - Region <X> - <OrganizationName>` is the requested org name format from "Visit Leads"

**Comment by joemienko** [comment]
@jessicamorris64 - UAT is ready for referrals. 

Can you please send 12 referrals?

- 6 regular referrals from each region, and 

- 6 72 hour referrals from each region?

Once they are sent, we will connect with @Deanna1968 for acceptance. 


-Joe

**Comment by joemienko** [comment]
We have working test referrals (test and emergent) for all 6 regions. 

All routing behaving as expected on UAT and accepted by @Deanna1968

**Comment by joemienko** [comment]
The proposed change has been implemented in production. 

Remaining steps are as follows: 

(Checked boxes are complete, unchecked boxes to be completed by Thursday (7/22), COB)

- [x] @sarahyatsko - Ensure that all contracts are set per provider preferred business processes on production
- [x] @sarahyatsko  - Add the complete set of 72 hour orgs that we would like on usertest 
- [x] @Deanna1968 - advise when providers have signed contracts
- [x] @sarahyatsko  - Set usertest contracts to match the full set of business processes on production
- [x] @joemienko - update all 72 hour orgs to routing orgs within the UI
- [x] @joemienko - give DCYF contracts with all 72 hour orgs
- [x] @joemienko - give tribal partners contracts with all 72 hour orgs
- [x] @yhtill to update the usertest routing tables
- [x] @sarahyatsko create 1 or more orgadmin account in each 72 hour org
- [x] @sarahyatsko create 1 or more regionadmin accounts in each 72 hour org
- [x] @sarahyatsko create contracts with FIN 72 hour org and all FIN subcontractors

In addition to the above, the following items need to be completed by July 25, 2020, shortly after 12:00AM when the period of performance for 72 hour org begins in their new contracts. 

~~Since Sprout and FamLink are both ready to receive 72 hour referrals as of July 23, 2020, CSSAT will monitor the queues of 72 hour orgs as indicated below for misdirected referrals (i.e. referrals that a social worker desired to send to the 72-hour orgs prior to the period of performance). If any misdirected referrals are observed before July 25, 2020, shortly after 12:00AM, CSSAT will reassign the misdirected referral to the appropriate VC with the following note: "EMERGENT REFERRAL REQUESTED PRIOR TO THE START OF 72 HOUR CONTRACT, PLEASE PROCESS AS AN INITIAL REFERRAL~~

- [ ] @jessicamorris64  - send training referrals to usertest to facilitate training without PII (ASAP after DST06 is updated)

~~- [ ] @joemienko - check for any misdirected 72hour referrals and reassign to regular VCs (Friday by 3PM)~~
~~- [ ] @joemienko - check for any misdirected 72hour referrals and reassign to regular VCs (Sunday shortly after midnight)~~

**Comment by joemienko** [comment]
As per business guidance on Thursday

> FamLink changes have been made and will go live at 6:00am on 7/23/21; however, the routing system to Sprout will not go live for this referral process until 12:01am on 7/25/21. Referrals cannot be made for the 72-hour referral until this time. If a referral is made prior to this timeframe it will not route to the contractor. HB 1194 effective date is 7/25/21.

We have reconfigured Sprout to comply with the above policy as written.

**Comment by Deanna1968** [comment]
Thank you Joe!

**Comment by joemienko** [comment]
> Thank you Joe! From: joemienko ***@***.***> Sent: Thursday, July 22, 2021 6:49 PM To: cssat/sprout-issues ***@***.***> Cc: Morrison, Deanna (DCYF) ***@***.***>; Mention ***@***.***> Subject: Re: [cssat/sprout-issues] VC orgs will slow down 72 hour referrals (#172) External Email As per business guidance on Thursday FamLink changes have been made and will go live at 6:00am on 7/23/21; however, the routing system to Sprout will not go live for this referral process until 12:01am on 7/25/21. Referrals cannot be made for the 72-hour referral until this time. If a referral is made prior to this timeframe it will not route to the contractor. HB 1194 effective date is 7/25/21. We have reconfigured Sprout to comply with the above policy as written. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcssat%2Fsprout-issues%2Fissues%2F172%23issuecomment-885345728&data=04%7C01%7CDeanna.morrison%40dcyf.wa.gov%7Ceec18301aaee44ed546308d94d7bfeeb%7C11d0e217264e400a8ba057dcc127d72d%7C0%7C0%7C637626017245087441%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=tsD7wFJEn0STRRc8nfurUUNREJTTRUZFXeGxrz0h6M0%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAOQSHBTY6OQBPQIS2X4FPCTTZDC7PANCNFSM47KRPF2A&data=04%7C01%7CDeanna.morrison%40dcyf.wa.gov%7Ceec18301aaee44ed546308d94d7bfeeb%7C11d0e217264e400a8ba057dcc127d72d%7C0%7C0%7C637626017245087441%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Q9SfxUrlnEAbgEpEWh5O8x1PiY5VJegsaKDmGeo7Rk8%3D&reserved=0>.
