### ISSUE TITLE
When a child does not visit within 3 days of OPD, we don't know why

### ISSUE THREAD

**Issue by joemienko** [cssat/sprout-issues#177]

**Comment by joemienko** [comment]
HB 1194 requires that children visit their parents within 72 hours of being delivered into the custody of DCYF. When children don't have an initial visit within that time frame, we need to know why.

Current plans to resolve this issue are to create an "initial visit log" within the visit referral that can be accessed from the summary view as shown below: 

![image](https://user-images.githubusercontent.com/37134346/129595182-bab663a4-1353-4588-893a-c4c7565540ec.png)

The log will indicate the total number of children on the referral and the number of initial visit outcomes registered. The goal is to have an initial visit outcome registered for each child. 

Clicking the Edit button will open a modal similar to the one below. 

![image](https://user-images.githubusercontent.com/37134346/129595407-0888f241-32c5-497b-a231-b3f1c359c2e8.png)

For children who visited, the user will indicate that they have visited. For children who did not have an initial visit, the user will be allowed to select from a list of reference values (e.g., "72 Hour Visit Did Not Occur - Parent No-Showed). 

Within the modal...

- Users cannot add children
- Users cannot delete children
- Users cannot change the first or last name
- Users can specify an outcome value for each child

NOTE: Longer-term feature request is to automatically register an initial visit outcome for children who show up on a visit report.

**Comment by joemienko** [comment]
@sarahyatsko @jessicamorris64  - Can you guys please get us a list of "reasons the 72 Hour Visit Did Not Occur"?

Thanks!

**Comment by jessicamorris64** [comment]
It was my understanding that Sarah and Deanna were going to work with Providers to gather that list. but I could be wrong. 
In additional to the list, I'm not sure the label make sense, we went to great lengths to establish the difference in initial vs emergent 72 hour. so calling this the initial visit outcome doesn't make sense to me...

**Comment by subaykan** [comment]
done with https://github.com/cssat/sprout/pull/107

**Comment by cdoran99** [comment]
Reviewed and approved by Jessy on 01/28/2022
