### ISSUE TITLE
Providers can not enter more than 2 Hours of Time for an Intake

### ISSUE THREAD

**Issue by tim123k** [cssat/sprout-issues#178]
**Describe the bug**
The time field for an intake in Sprout will not allow the user to enter a number greater than 2.0

**Expected behavior**
No 2.0 cap on allowed time entered for intakes so that users can enter the total time they actually spent on intake, even when that is longer than 2 hours.

**Comment by subaykan** [comment]
Done

PR: https://github.com/cssat/sprout/pull/112

**Comment by cdoran99** [comment]
Reviewed and approved by Jessy on 01/28/2022
