### ISSUE TITLE
Unable to download pdf of incomplete CANS

### ISSUE THREAD

**Issue by sarahyatsko** [cssat/sprout-issues#179]
Sometimes it would be helpful to be able to download the pdf for a CANS that is only partially complete.  As the application now works, the download button is only visible if at least one portion of the CANS is completed. 

**Describe the solution you'd like**
Make download button visible and functioning at all times, even when nothing is entered in the CANS. 

**Describe alternatives you've considered**
Maybe some sort of warning that the section of the CANS is incomplete, which is why the download is not an option. 

@sarahyatsko will check with Delton to ensure this approach is the right one.

**Comment by subaykan** [comment]
https://github.com/cssat/sprout-wizard/pull/47

**Comment by cdoran99** [comment]
Reviewed and approved by Jessy on 01/28/2022
