### ISSUE TITLE
The UIR Report in UI in Sprout says "CA" instead of "DCYF"

### ISSUE THREAD

**Issue by sarahyatsko** [cssat/sprout-issues#180]
**Describe the bug**
There are at least two places in the UIR screen in Sprout that says "CA" where is should say "DCYF"

![Screen Shot 2021-10-13 at 3 54 36 PM](https://user-images.githubusercontent.com/49733235/137223812-a4603077-d929-4ea8-8d66-7239e26cd02a.png)

**Comment by subaykan** [comment]
https://github.com/cssat/sprout/pull/111

**Comment by cdoran99** [comment]
Reviewed and approved by Jessy on 01/28/2022
