### ISSUE TITLE
Sort referrals by 'request date': null Original request date is ordered first

### ISSUE THREAD

**Issue by subaykan** [cssat/sprout-issues#183]
repro example: enter case number into search field: 1907606
select 'Request Date' in Sort pulldown. 
The first result in the sorted list is older than the rest (the remaining are sorted correctly)

clicking into that referral's details shows that the Original request date is missing (this is called out with error messaging on the referral). This is most likely an error on the input (referral data ingestion) and not a bug within sprout.  However, there are likely other fields that can be used as failover sort criteria when ordering by date.  

This is a low impact issue and probably quite rare, just capturing here to make a record of it.

**Comment by subaykan** [comment]
would be a good fix to relieve providers' pain point

**Comment by keithligon** [comment]
deployed as part of https://github.com/cssat/sprout/releases/tag/production-20230615191254

resolving.
