### ISSUE TITLE
UIR 'other action taken' field silently fails on length > 255

### ISSUE THREAD

**Issue by subaykan** [cssat/sprout-issues#185]
Brought to our attention via zendesk tickets:
https://oliver.zendesk.com/agent/tickets/17281
https://oliver.zendesk.com/agent/tickets/17289 

**Describe the bug**
In an Unusual Incident Report (UIR), in the 'Action taken' section, selecting 'Other' in the Action Taken pulldown surfaces the text input field for a description of the action taken.  The database column storing this value is a 255 varchar, and entering a value exceeding that length was causing a silent error that did not alert the user about the problem. The user was then unable to submit the UIR and did not know why.

**Comment by subaykan** [comment]
fix: https://github.com/cssat/sprout/pull/113

added max length of 200 to the validation schema of the form.

**Comment by subaykan** [comment]
deployed to UAT

**Comment by cdoran99** [comment]
Thank you John. our team can review shortly and report back on how the testing is going.

**Comment by subaykan** [comment]
Note: we got signoff to deploy this fix from Doug yesterday - and will be deploying to prod today or tomorrow. 

Some info about the functionality and the scenarios: if the length of the 'other action taken' field exceeds 200, the browser will still be able to save the form including that field (up to a max of 255), but the validation failure (i.e. the red error message) will not allow the report to be ready for the **Approve** step.  This field will have to be cut down to a max length of 200 in order for the report to be staged for the approval.

**Comment by jessicamorris64** [comment]
Hey John,
Just making sure I understand, it prevents supervisor approval right? The worker is still able to submit it to supervisor from what we saw yesterday.

**Comment by subaykan** [comment]
@jessicamorris64 - yes, to be clear - it disables the Approve button. The data in the form can be saved/submitted but can not be approved until the form validation error is resolved (in other words, that field cut down to 200 or below)

**Comment by subaykan** [comment]
deployed to prod and verified fix

**Comment by jessicamorris64** [comment]
Fabulous! Thanks John! 😊
