### ISSUE TITLE
Sprout Users Must Click Edit to See Certain Referral Information on Referral Screen

### ISSUE THREAD

**Issue by sarahyatsko** [cssat/sprout-issues#187]
**Describe the bug**
In the section of the referral titled "Schedule" there is a subsection titled "Time Negotiable" It looks like there are two fields in this subsection and it may be that if the first field is left blank in FamLink, then the entire Time Negotiable field does NOT show up on the main referral screen in Sprout. 

**To Reproduce**
Open the referral in Sprout with the Visit Plan ID of 1571075
1. Go to referral
2. Scroll down to the Schedule section - see that there is no Time Negotiable sub-section
3. Click on the blue edit button to the right
4. See that there is information in the Time Negotiable sub-section that was not showing on the main referral page

**Expected behavior**
The second field should probably still be visible in the main referral page, even if the first field is blank

**Screenshots**
<img width="1090" alt="Screen Shot 2022-01-27 at 3 37 16 PM" src="https://user-images.githubusercontent.com/49733235/151462653-eb6a7234-6366-4e0e-94a9-e4fe4d5bc4fd.png">

<img width="1096" alt="Screen Shot 2022-01-27 at 3 54 47 PM" src="https://user-images.githubusercontent.com/49733235/151462809-2d3d5067-ebfd-41cf-8d7a-9b74377c8686.png">
<img width="1043" alt="Screen Shot 2022-01-27 at 3 55 00 PM" src="https://user-images.githubusercontent.com/49733235/151462811-c07eb673-19e6-4894-9011-4f7b30764190.png">

**Comment by subaykan** [comment]
Investigating, some notes:

comparing the referral noted in this bug 
https://www.sproutservices.org/visitation/referrals/61246
with another where the court order notes are displayed on the read view:
https://www.sproutservices.org/visitation/referrals/61217

in the latter, the 'Time Negotiable' field has the value 'Court Ordered' whereas the problem case cited has no value. I suspect the problem (of the notes not being displayed) is that this value is missing.

Looking into this..

**Comment by subaykan** [comment]
in referral 61246 the UI shows this value for court order notes: 
![Screenshot from 2022-01-28 11-41-01](https://user-images.githubusercontent.com/80794129/151611048-f18f8a54-18a8-43ff-9bed-dcff72b73289.png)

and for 61217 the UI is shown in the screenshot
<img width="1043" alt="Screen Shot 2022-01-27 at 3 55 00 PM" src="https://user-images.githubusercontent.com/49733235/151462811-c07eb673-19e6-4894-9011-4f7b30764190.png">



```
db=# select id, "visitPlanId", "versionId", "timeNegotiable", "courtOrderNotes" from "ServiceReferrals" where id in (61246,61217) and "isCurrentVersion";
  id   | visitPlanId | versionId | timeNegotiable |                                 courtOrderNotes                                 
-------+-------------+-----------+----------------+---------------------------------------------------------------------------------
 61217 | 1571074     |   1025945 | Court Ordered  | 4x per week for 1.5 hours
 61246 | 1571075     |   1017173 |                | Father is court ordered 1 monthly overnight visit.\r                           +
       |             |           |                | \r                                                                             +
       |             |           |                | SW is requesting 2 weekly virtual visits for 30 minutes to an hour per visit.\r+
       |             |           |                | \r                                                                             +
       |             |           |                | Visits in-person are now unsupervised.
(2 rows)

```

the problem referral is missing the `timeNegotiable` value

**Comment by subaykan** [comment]
also noting that older referrals do not look the same in the UI in edit view, I think there was a change to the data format for referrals at some point, older referrals (and dev data) look like this:

![Screenshot from 2022-01-28 11-58-41](https://user-images.githubusercontent.com/80794129/151613257-c4d321fe-3af9-4d81-aa85-ed584cde7225.png)

... looks like there is a distinction between referrals that render this from either:
`client/app/visitation/components/ServiceReferral/Types/Ingested/Pages/Schedule/index.jsx`
or
`client/app/visitation/components/ServiceReferral/Types/Shared/Pages/Schedule/index.jsx`

edit:

I see this is driven by `formVersion` in the data:
in older referrals, this `formVersion` is March 2015 or March 2016. (like charlie brown below)

```
db=# select id, "formVersion", "visitPlanId" from "ServiceReferrals" where id in (61246,61217,425) and "isCurrentVersion";
  id   | formVersion | visitPlanId 
-------+-------------+-------------
   425 | March 2015  | 
 61217 | Ingested    | 1571074
 61246 | Ingested    | 1571075
(3 rows)
```

**Comment by subaykan** [comment]
I can now repro this in dev by manipulating a dev record to `formVersion`=Ingested, and `timeNegotiable` set to 'Court Ordered' and adding a `courtOrderNotes` value, then setting `timeNegotiable` to null.

The questions I have are:

1. If the `timeNegotiable` field in an ingested referral is null, what does that suggest? Is that an error from the Famlink side?
2. If `timeNegotiable` is null, should `courtOrderNotes` be displayed anyway? (We can do that by replacing a null/undefined with a space character but I'm not sure if that is what we should do) 


I see that we are checking strictly for these values in the ingestion, so if there is no 'Y' or 'N' or no court order field, we don't default, and timeNegotiable is set to undefined, and saved in db as NULL.  So that suggests bad input from Famlink in this case. Not sure if we should mitigate for this on our side - i.e. show the court order notes in any case. ?

```
  const yes = (get(sourceData, 'FL_NEGOTIABLE[0]') === 'Y')
  const no = (get(sourceData, 'FL_NEGOTIABLE[0]') === 'N')
  const courtOrder = (get(sourceData, 'TX_COURT[0]').length > 0)

  let timeNegotiable
  if (yes && courtOrder) {
    timeNegotiable = 'Court Ordered'
  } else if (yes) {
    timeNegotiable = 'Yes'
  } else if (no) {
    timeNegotiable = 'No'
  }
```

**Comment by subaykan** [comment]
raw XML of the incoming case shows empty in that field as we suspected:

```
    <FL_NEGOTIABLE></FL_NEGOTIABLE>
    <TX_NEGOTIABLE />
    <TX_COURT>Father is court ordered 1 monthly overnight visit.

SW is requesting 2 weekly virtual visits for 30 minutes to an hour per visit.

Visits in-person are now unsupervised.</TX_COURT>
```

notes, steps to get this:

```
$ psql postgresql://<APTIBLE_CONNECTION_STR>/db -c '\copy (SELECT referral_data FROM external_referral_data WHERE referral_id = XXXXX AND deleted_at IS NULL ORDER BY version_id DESC LIMIT 1) to STDOUT'  | xxd -p -r > xmldata 
```

script:
```
const zlib = require("zlib");
const fs = require("fs");

fs.readFile("<PATH_TO>/xmldata", (err, data) => {
  const xmlstr = zlib.inflateSync(data).toString();
  console.log(xmlstr);
});
```

```
$ node SCRIPTNAME.js  > OUTPUT.xml
$ xmllint --format OUTPUT.xml 
```

**Comment by nelsosd** [comment]
I took a look at the Referral that is downloaded from Sprout, and found the Court Data on it is exactly where it is on the FamLink Referral.
***@***.***

It’s just not showing on the UI version of Sprout. So we know Sprout has it, but it doesn’t display it.


Shannon Nelson, MSW/IT Technology Trainer
Technology Services
253-380-5273<tel:253-380-5273>/ ***@***.******@***.***>
***@***.***<http://www.dcyf.wa.gov/>

**Comment by subaykan** [comment]
Hi @nelsosd : Sorry for causing a bit of confusion. Yes, that data is in the DB. 

My comment which says "however I don't see the data for the latter in the DB" is outdated, I had mistyped the ID and saw wrong results.  My more recent findings are noted above, and they show that:

1. the court order notes for referral 61246 (visit plan 1571075) are indeed in the Sprout DB
2. the xml ingested into Sprout for that visit plan is missing the value in this field: `<FL_NEGOTIABLE></FL_NEGOTIABLE>` (the system is expecting to find either a `Y` or `N` in that field)

This is causing the court order notes to not be displayed, we are discussing what the right action is to mitigate that.

**Comment by subaykan** [comment]
fix PR: https://github.com/cssat/sprout/pull/114

**Comment by jessicamorris64** [comment]
reviewed and approved by Jessy to move to prod 2/2/22

**Comment by subaykan** [comment]
Deployed to prod 2/3/22 and verified the fix
