### ISSUE TITLE
Driver's Name on an Approved Report Disappears After their Sprout Account is Disabled

### ISSUE THREAD

**Issue by sarahyatsko** [cssat/sprout-issues#188]
**Describe the bug**
When a provider organization in Sprout disables a particular user account, it appears as though that user's name is wiped off the driver portion of all reports in Sprout - even if the report was fully approved and submitted. 

**To Reproduce**
Start a visit report
Put a name in the driver field
Complete the visit report
Submit the Visit Report
Approve the Visit Report
Disable the Sprout account for the person listed as the driver in the report
Check the approved report, and the driver's name will be erased

**Expected behavior**
Driver's name will remain on the report even if the driver's Sprout account is disabled.

**Comment by subaykan** [comment]
digging into this, some notes:

`client/app/visitation/components/VisitReport/Summary/Fieldsets/VisitTransportDetails/Item/Layout.jsx`

```
const VisitTransportDetailsItem = ({ item, index, driversDataSource }) => {
...
      <div>
        <DataSelect
          selector={selector}
          field="driver"
          label="Driver:"
          source={driversDataSource}
        />
      </div>
```

this `driversDataSource` is the url to get the list of available (approved) users, it boils down to here:
```
VISIT_REPORT_ASSIGNABLE_USERS_DATA_SELECT_URL = (id) => `/api/visitation/visit-reports/${id}/assignable-users`
```

however it doesn't make sense to me why the summary page uses this, when the visit report has the user id in the `driver` field of the `transportDetails` in the database

```
poc_development=# select jsonb_pretty( "transportDetails"::jsonb ) from "VisitReports" 
where id = 12 and "isCurrentVersion";

-[ RECORD 1 ]+---------------------------------------------
jsonb_pretty | [                                           +
             |     {                                       +
             |         "child": "boobobo",                 +
             |         "driver": "7",                      +
             |         "transportEndTime": "1:00 PM",      +
             |         "transportDistance": "2",           +
             |         "transportStartTime": "12:40 PM",   +
             |         "directionOfTransport": "From visit"+
             |     }                                       +
             | ]
```

in this case the user id `7` points to the record in Users table id=7, but if that user is `disabled` and not `approved`, it is not listed in the above assignable users and that data source passed into the DataSelect component does not find it. 

Seems like that data does not need to be loaded through the DataSelect component.

**Comment by subaykan** [comment]
deployed to prod 2/24

**Comment by jessicamorris64** [comment]
forgot to say i approved this on 2/23 during John's demo.
