### ISSUE TITLE
New DCYF Admin Org

### ISSUE THREAD

**Issue by jessicamorris64** [cssat/sprout-issues#191]
this is an official request for the new DCYF Admin Org to be created in Sprout Prod. Jessica Morris can temporarily be placed as the org admin for this organization until those duties can be passed on to another.
this organization will be used for DCYF Field IT to manage all DCYF basic user and visit coordinator accounts on going. it must be able to enable and disable users from it's organization and from all visit VCR organizations along with the DCYF Basic user organization.
Sarah Y and John S were able to create this organization in user test and Jessica Morris tested it with SUCCESS!!! :)
if you have any other questions please contract jessica.morris@dcyf.wa.gov (or Sarah I'm sure she has answers too )
thank you
jessy

**Comment by subaykan** [comment]
this org was created, closing this item
