### ISSUE TITLE
Additional Rate Changes

### ISSUE THREAD

**Issue by jessicamorris64** [cssat/sprout-issues#192]
NEW
What are you trying to solve:
Legislature is no longer willing to fund certain family time items. There are changes to the following rates. Missed visit reports (both No Show and Cancelled Less than 24) will now be not paid ($0). Unusual incident Reports will now be paid out at 10 minutes at the rate of $26.50 ($4.42). Attended visit report will now be paid at 30 minutes at the rate of $26.50 ($13.25). No show in person visit and virtual visit will not be paid ($0). Cancelled less than 24 hour in person and virtual visits will not be paid ($0). This would need to be ready to go out for October Statements.
--

OLD
How is work completed today?
Missed visit report is currently 29 minutes at $26.50 ($13.02). Unusual incident report is 32 minutes at $26.50 ($14.12). Visit report is 45 minutes at $26.50 ($19.83). No show in person is 105 minutes at $26.50 ($46.49). No show virtual is 51 minutes at $26.50 ($22.53). Cancelled less than 24 hours in person is 120 minutes at $26.50 ($53.31). Cancelled less than 24 hour virtual 66 minutes at $26.50 ($29.15).

**Comment by subaykan** [comment]
Completed
