### ISSUE TITLE
Required fields for CANS-F

### ISSUE THREAD

**Issue by jessicamorris64** [cssat/sprout-issues#197]
As a program manager I need to make sure the following fields on the CANS-F are required in order to have accurate data and correctly match the CANS-F to a case in FamLink.
this is a priority for the CANS-F program, OIAA, and Quality Assurance.

Require FamLink Service Referral ID
Require Referral Reason to be selected from existing drop down menu
Require Date of FPC completion
Require Date Referral Received
Require Date of Initial face-to-face
--

**Comment by chrishughes20** [comment]
Consolidating all input validation issues for CANS into this ticket.

#149 Comments field required when purchase amount entered
#148 Required fields and validation on the Plan for change page
#147 Child Name and Child Id should be required to save Assessment
~~#143 Indicate incomplete fields before navigating to another tab~~
#142 Required field indicator on Face Sheet
#140 “Date First In Person Meeting” should not be able to be before the “Date Referral Received”
#128 Date fields allow erroneous date input (invalid dates get deleted but no error messages)
#127 Services paid field allows erroneous data input

**Comment by subaykan** [comment]
#148 to be reviewed by CANS collaborators
#143 : not required to block user from navigating off tab when required input is not yet entered

**Comment by chrishughes20** [comment]
Deployed

**Comment by subaykan** [comment]
related to #208 from DCYF list
