### ISSUE TITLE
List of Outcomes for 72 Hour Referrals is Incomplete

### ISSUE THREAD

**Issue by sarahyatsko** [cssat/sprout-issues#203]
_Email request from Doug Allison
July 11, 2023

In sprout data dictionary we discussed at sprout mtg. ca we add a sprout request to add to the 72 hr visit reasons
 
Visit completed within 5 days
Unable to provide the visit . 
 
Doug Allison, Administrator Services and Navigation Unit_

Additional Context: 
**Is your feature request related to a problem? Please describe.**

There is an “Outcome" field in Sprout that only appears on 72 hour visit referrals. When a provider resolves a 72 hour referral, they are asked to chose an “outcome” for the referral from a dropdown list (screen shot attached.) The current options for providers to select are limited to either “Visit Completed Within 3 Days of Placement” or 16 other options, each of which are reasons the visit was not completed within 3 days that are all outside of the control of the provider (i.e. Parent Refused, Caregiver Contact Information Incorrect, etc)  In other words, there is no way for a provider to indicate that they did not complete the visit successfully due to something the provider themselves failed to do (i.e. no staff available.) . 

A few added notes on Doug’s language. He references the “sprout data dictionary” here (which I suppose this would ultimately impact as Barb and the OIAA team will get this data so the new options should be in the data dictionary) but this is a request to make a change to the Sprout UI. 

Also, the options Doug lists here will need to be wordsmithed a bit.  He lists:

Visit completed within 5 days
Unable to provide the visit . 
 
The option "Visit Completed Within 5 Days" might be confusing and it also does not clarify the "why". It may also be unnecessary as the visit date will show when the visit happened and whether it was within 3 or 5 days.  And “unable to provide the visit” option should be clarified to mean that the provider was at fault specifically for not providing the visit within 3 days, otherwise providers may select it incorrectly. 

<img width="323" alt="Screenshot 2023-07-19 at 11 10 19 AM" src="https://github.com/cssat/sprout-issues/assets/49733235/f25294a4-f5ec-4c89-978b-8a8c640a6679">

**Comment by subaykan** [comment]
deployed with https://github.com/cssat/sprout/pull/148
