### ISSUE TITLE
Update visit report forms

### ISSUE THREAD

**Issue by joemienko** [cssat/sprout-issues#21]

**Comment by joemienko** [comment]
These are the forms DCYF is looking to have updated. 

[15-454 final.docx](https://github.com/cssat/sprout-issues/files/3795666/15-454.final.docx)
[15-451 final.docx](https://github.com/cssat/sprout-issues/files/3795667/15-451.final.docx)
[15-452 final.docx](https://github.com/cssat/sprout-issues/files/3795668/15-452.final.docx)
[15-450 final.docx](https://github.com/cssat/sprout-issues/files/3795669/15-450.final.docx)
[15-448 final.docx](https://github.com/cssat/sprout-issues/files/3795672/15-448.final.docx)
[15-363B final.docx](https://github.com/cssat/sprout-issues/files/3795673/15-363B.final.docx)

**Comment by yhtill** [comment]
Waiting for an updated visit referral form from DCYF.

**Comment by joemienko** [comment]
We prefer to do this all as a single project. 

Waiting on revised intake form from DCYF

**Comment by sarahyatsko** [comment]
Adding the Referral Form and the Visit Notes (Report?) form as sent to me today by Deanna Morrison. 

[Family Time Referral Feb 2020.docx](https://github.com/cssat/sprout-issues/files/4269730/Family.Time.Referral.Feb.2020.docx)
[Family Time Visit Notes Feb 2020.docx](https://github.com/cssat/sprout-issues/files/4269731/Family.Time.Visit.Notes.Feb.2020.docx)

**Comment by jessicamorris64** [comment]
Thanks Sarah

**Comment by joemienko** [comment]
We need to add this to our "form management/rendering" epic

**Comment by joemienko** [comment]
@cssatmcfunk The following list references file names above. These are the most recent forms received from @Deanna1968. 

15-363B - Intake Screening Report
Family Time Referral Feb 2020.docx - Referral Report
Family Time Visit Notes Feb 2020.docx - Visit Report (Regular)
15-452 - Sibling Visit Report
15-451 - Missed Visit Report
15-454 - UIR Report

Ensure that none of the forms have DCYF form numbers or revision dates...

**Comment by jessicamorris64** [comment]
Marshall loaded revised forms to UAT on 4/28 they were reviewed on 4/29 by Shannon and Jolene.
there appear to be some fields missing that are required in order to meet the needs of the discovery and disclosure staff. also some formatting changes outlined in the attached word document.
this will also need to be produced in PDF version and not word.
Marshall has reviewed the document and is currently working on edits to meet the requirements.

[visit-report_Sprout.docx](https://github.com/cssat/sprout-issues/files/4554698/visit-report_Sprout.docx)

**Comment by joemienko** [comment]
@Deanna1968 

The attended visit reports are ready for acceptance, other printable forms will be ready for acceptance soon. For the attended please 

1. see the following user story 

_As a Sprout user/stakeholder with access to attended visit reports, I want to see all available information on printed/downloadable visit reports, so that viewers of the visit reports without access to sprout can see all available details related to a visit report._ 

2. Please confirm the following acceptance criteria for this story

**Given**: that a visit report is viewable
**And**: the user has attempted to download a printable version of the referral
**When**: the user views the printable version of the referral
**Then**: the user will see all available attended visit report details associated with that report

**Comment by Deanna1968** [comment]
I don't accept this feature as the form is not completed.  

Deanna Morrison

**Comment by joemienko** [comment]
@cssatmcfunk - @Deanna1968 can't accept this until we add the remaining fields. See the email from Shannon

**Comment by joemienko** [comment]
As of today, we believe that all fields have been added. 

The following forms are ready for acceptance: 

1. Attended Visit Reports
2. Missed Visit Reports
3. Sibling Visit Reports
4. UIR

@Deanna1968, Please review each of these forms according to the acceptance criteria above. 

Need to talk at our check-in today about how to proceed with 

1. The referral form, and 
2. The intake form. 

Regarding the referral form, the information contained on the current form is not limited to information that came in the "referral". Should we separate "FamLink" and Sprout data on this form?

Regarding the intake form, providers are still being asked to add information to the DOCX after the download is generated. 

-- Should this be kept as a DOCX? (see #84)
-- Should we separate the intake out as its own "report form"?

**Whatever we decide to do with these two forms...
We should separate these forms as two separate issues.**

**Comment by Deanna1968** [comment]
Joe, 

super dumb question....were am I suppose to review them at?  In Sprout or ......sorry, you computer and tech wizards get me every time!  OR If I am to accept how they are listed above...I accept!  

sorry

**Comment by nelsosd** [comment]
Deanna, we’re reviewing them in Sprout UAT.

Shannon Nelson, MSW/IT Technology Trainer
Technology Services
253-380-5273<tel:253-380-5273>/ Shannon.nelson@dcyf.wa.gov<mailto:Shannon.nelson@dcyf.wa.gov>
[cid:image003.jpg@01D53D58.43DF9440]<http://www.dcyf.wa.gov/>

**Comment by Deanna1968** [comment]
You Have a New State of Washington Secure Email Portal Message 

"Morrison, Deanna (DCYF)" <deanna.morrison@dcyf.wa.gov> has sent you an encrypted message via State of Washington Secure Email Portal.

   Subject: RE: [cssat/sprout-issues] Update visit report forms (#21)
   Sent: May 14, 2020 11:38:45 AM, PDT

ACTIVATION INFORMATION:

The State of Washington Secure Email Portal has changed providers. You will need to create a new account to access your message. We apologize for the inconvenience. Once you've created your account, you can view your messages you receive from "Morrison, Deanna (DCYF)" <deanna.morrison@dcyf.wa.gov> directly from your State of Washington Secure Email Portal account:

   Email: reply@reply.github.com
   MESSAGE EXPIRY: June 13, 2020 11:38:52 AM, PDT
   You have 30 day(s) left to collect this message before it expires. Once the message
 expires, it will be permanently removed from the server.
   Click here to create your account and read your message: https://emailencryption.twsegcloud.com/login.html?msgUserId=615b1a78853df122&enterprise=trustwave_watech&rrRegcode=VTn9ZYfc&locale=en_US

NEED HELP?

Need help? Visit the State of Washington Secure Email Portal https://emailencryption.twsegcloud.com/branding/trustwave_watech/en_US/help/index.html

**Comment by jessicamorris64** [comment]
you will need to review in UAT before you approve...

**Comment by joemienko** [comment]
Need to ask Rhonda if we stage Referral and Intake form revisions to allow us to reduce the sprout referral concept to "those data elements from FamLink", and create a new "Report" that would handle the provider intake business process.
