### ISSUE TITLE
Hide ZZZ orgs from lists

### ISSUE THREAD

**Issue by subaykan** [cssat/sprout-issues#218]
We should actually have a better way of deactivating organizations, but as a stopgap let's filter out organizations whose names begin with 'ZZZ - Deactivated' from populating lists:
The organization filter in search
The register form
The contracts listing of orgs
The 'all organizations' listing of orgs

see also #60

**Comment by chrishughes20** [comment]
PR that addresses this issue: https://github.com/cssat/sprout/pull/162
