### ISSUE TITLE
Reject report sometimes leads to blank page

### ISSUE THREAD

**Issue by tinhart** [cssat/sprout-issues#238]
**Describe the bug**
Kurt and Angela's showed us how sometimes when he hits REJECT on a report, Sprout then displays a blank screen instead of returning to the tile view of the reports. There may also be am issue from a previous bug fix affecting this... (see second screenshot - Kurt reported issue).

<img width="1262" alt="REJECT blank screen findings" src="https://github.com/cssat/sprout-issues/assets/147194389/ae865b94-bbdd-44e0-83a6-422d30f5bcc0">

<img width="1032" alt="Kurt reported issue (after rejecting visit report)" src="https://github.com/cssat/sprout-issues/assets/147194389/3d7d2656-1b86-483d-947e-d666f735bc00">

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by keithligon** [comment]
This was addressed with https://github.com/cssat/sprout/commit/0c3f4a9854f685a6f0cad020e2e38079220d16fd

**Comment by tinhart** [comment]
Closing this bug as "resolved" as per Keith's confirmation: cssat/sprout@0c3f4a9
