### ISSUE TITLE
List of DCYF providers

### ISSUE THREAD

**Issue by joemienko** [cssat/sprout-issues#26]
**Please describe the information you need in your report.**
David Sexton has requested a list of organizations that are 1. Active, and 2. Have a contracted relationship with the DCYF organization. 

**Is your report request a one-time request, or a query that will be needed on-demand in the future?**

On-Demand

**Please describe the business need for your report.**
To audit providers with access to Sprout.

**Comment by yhtill** [comment]
This is already visible through Sprout UI.
