### ISSUE TITLE
Banners disappearing on activity sort

### ISSUE THREAD

**Issue by joemienko** [cssat/sprout-issues#34]
**Describe the bug**
The resolved banner is disappearing on activity sorts

**To Reproduce**
1. Go to Referral List
2. Sort by report activity
3. Resolved banner does not show

**Expected behavior**
1. Go to Referral List
2. Sort by report activity
3. Resolved banner does show

**Comment by yhtill** [comment]
I'm still unclear on how to reproduce this.

**Comment by joemienko** [comment]
This has been reproduced and is waiting to be picked up by the engineering team

**Comment by cdoran99** [comment]
We are no longer seeing this issue occur. Thank you
