### ISSUE TITLE
Need to add a placement end reason field to the referral

### ISSUE THREAD

**Issue by joemienko** [cssat/sprout-issues#41]

**Comment by joemienko** [comment]
As 1/23, this was still being tested by @jesse. 

We will need confirmation that the new XML is being pushed (or a sample of what the XML will look like) before we get started on this.

**Comment by joemienko** [comment]
Per Jesse this will be in the XML on February 7. No longer being blocked by DCYF.

**Comment by joemienko** [comment]
@oieeri26 - The desired resolution of this issue is as follows: 

Within `childPlacedInfo`, in the ingested referrals, we should be receiving a placement end reason from the ingested XML. 

The referral end reason should be specifically located in the `visitPlan/CHILDREN_PLACED/childPlacedInfo` section of the XML. 

The placement end reason needs to be 

1. Added to `root/childPlacements` on the referral, and
2. Displayed to an end user, as an uneditable field, within the `childPlacements` portion of the referral UI - both on 
a. the referral form, and 
b. in the referral summary.

**Comment by joemienko** [comment]
@oieeri26 - Update to the above...

It looks like DCYF is going to do the work of determining TRH for us. IOW, there is going to be a TRH flag provided in the XML, not a placement end reason...

Also, the TRH flag is going to be in the Child Details section of the XML, not the Placement Information. 

Thus (I think) you are going to want to update the child details transformer here: `sprout/api/api/util/import/famlink/transformers/childDetails.js` instead of `childPlacements.js`.  

This would (I think) add the TRH content from the XML to the `childDetails` column of `ServiceReferrals` when the TRH element is populated i.e.
 
`<TRIAL_RETURN_HOME>Y</TRIAL_RETURN_HOME>
`
and do nothing when it is not populated i.e. 

`      <TRIAL_RETURN_HOME />
`

Example XML files (with no real PII) are available below. One with no TRH information, and one with. GitHub won't let me attach xml files or files without extensions, so you'll need to change the txt to xml on your own...

[exampleFamlinkReferralNOTRH.txt](https://github.com/cssat/sprout-issues/files/4333026/exampleFamlinkReferralNOTRH.txt)
[exampleFamlinkReferralTRH.txt](https://github.com/cssat/sprout-issues/files/4333027/exampleFamlinkReferralTRH.txt)

You can test whether changes you make to the transformer are working in your dev environment by using the "upload referral" option shown in the image below. You will prob need to be a superadmin to do that. 

![image](https://user-images.githubusercontent.com/37134346/76686654-3c781500-65da-11ea-951f-9d3f4e7e1559.png)

@jessicamorris64 - Two questions for you

1. Will the TRIAL_RETURN_HOME flag come over as Y/N as I have assumed above, or will it contain some other content? (see separate email to Jing/John from the date of this comment), 
2. Since TRIAL_RETURN_HOME is coming over in the Child Details (i.e. not the placement info), can we assume that this will be dynamically turned off when the TRH fails (i.e. when the child goes back into foster care after the start of TRH event, but before the end of the underlying placement episode)? IOW, can the TRH flag turn off once it is turned on?

**Comment by joemienko** [comment]
@oieeri26  - Update per John's email earlier today, 

The XML value will be one of the following 4 values: 

1. `<TRIAL_RETURN_HOME />`
2. `<TRIAL_RETURN_HOME>Trial Return Home - Mother</TRIAL_RETURN_HOME>`
3. `<TRIAL_RETURN_HOME>Trial Return Home - Father</TRIAL_RETURN_HOME>` or 
4. `<TRIAL_RETURN_HOME>Trial Return Home – Legal Guardian</TRIAL_RETURN_HOME>`

Obviously, 2-4 imply a TRH event, our direction to send the Sprout user to the Parent address to determine where the child is located.

**Comment by joemienko** [comment]
@oieeri26 - Documenting here that John answered question 2 for @jessicamorris64 as well. 

The XML value is dynamic - it can switch between any of the four values above. 

Values 2-3 are an indication that the visit supervisor should look to the parent address for the child's current location. 

Value 1 is an indication that the child is in the care of the listed foster parent.

**Comment by joemienko** [comment]
@Deanna1968 - 

We believe that this issue has been resolved and is ready for acceptance. 

1. Please see the following user story

_As a Sprout user, I want to know when a child on a referral has been placed back in the home of their parents under a trial-return-home (TRH) so that I can look at the parent’s address on the referral, and determine the child’s current location._  

2. Please confirm the following acceptance criteria for this story
**Given**: that a child has been placed back with their parents in FamLink
**And**: the underlying dependency case has not yet been dismissed
**When**: the user views the Child Details tab/section on a Family Time referral
**Then**: the user is informed that the child is in a trial-return-home (TRH). 
**And**: the user can view the actual child location under the Parent/Visitor Details section of the referral.

**Comment by joemienko** [comment]
@Deanna1968 & @jessicamorris64 - We still need to have this accepted. 

@sarahyatsko - It probably makes sense for you to check on this from the provider perspective as well. 

@jessicamorris64 - I believe you moved a child to TRH in your FamLink UAT environment. Can you please advise @Deanna1968 (over secure email, if it is a real child) what Sprout referral she should be looking for to accept this feature?

**Comment by joemienko** [comment]
@jessicamorris64 will make some changes in FamLink UAT today. 
@Deanna1968  to review/accept tomorrow

**Comment by Deanna1968** [comment]
I have reviewed TRH that Jessi did in the UAT :) and I accept!

Yay! 

Deanna

**Comment by Deanna1968** [comment]
Never mind I take it back on the TRH. Will get back shortly.

**Comment by Deanna1968** [comment]
I reviewed the UAT on TRH and I approve!

**Comment by Deanna1968** [comment]
Hi Jessi, Joe and Marshal, 

I viewed the sib visit plan in UAT tonight.  It looked good to me and gave me the info I needed to view it. 

Was I suppose to tell you this in GitHub?

thanks
Deanna
