### ISSUE TITLE
Need to Sort for Visit Reports Needing Review

### ISSUE THREAD

**Issue by sarahyatsko** [cssat/sprout-issues#43]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Prioritization Process**

- [ ] Confirm the issue is a feature to which we want to devote resources. 

- [ ] Write user story in `as a (role) I want (something) so that (benefit)` format. 

- [ ] Label story Large, Uncertain, Small. If the story is too large, convert the story to a milestone/epic. 

- [ ] Label story as an [active backlog](https://github.com/cssat/sprout-issues/projects/1) issue (i.e. an issue on which we will be actively working).

- [ ] Prioritize the story relative to other items in the [active backlog](https://github.com/cssat/sprout-issues/projects/1).

- [ ] Review progress/priorities in weekly collaboration meeting.

**Comment by sarahyatsko** [comment]
Large providers have requested that there be way to limit the view (via sort or filter) to referrals with reports that are needing review. This would greatly save time as current process requires that they click through dozens of pages to find the referrals with reports to review. For a large provider with dozens of reports to approve a day, this can take several hours a day.

**Comment by subaykan** [comment]
closing as duplicate
