### ISSUE TITLE
There is no way for users to see a log of changes

### ISSUE THREAD

**Issue by joemienko** [cssat/sprout-issues#44]
**Is your feature request related to a problem? Please describe.**
Currently, we do not have a way to easily notify users of changes in Sprout. 

**Describe the solution you'd like**
We would like some sort of change log feature to help users check on recent changes when they are interested in doing so. 

**Describe alternatives you've considered**
We have considered periodic emails and an expanded "application has changed" banner to be vended to all users (not just those who are logged into the application). 

I (Joe) also explored the use of "headway". 

A sample list of some of the recent changes we’ve made are available here: https://headwayapp.co/sproutservices-changelog.

The list is not _per se_ all that impressive in the free version, but it does come (for free) with a release notes widget which they claim can be integrated via CSS with the following chunk.

```
<script>
  // @see https://docs.headwayapp.co/widget for more configuration options.
  var HW_config = {
    selector: ".CHANGE_THIS", // CSS selector where to inject the badge
    account:  "JrBz0J"
  }
</script>
<script async src="https://cdn.headwayapp.co/widget.js"></script>
```
Was thinking the widget could be a way that people could (with GDPR compliance) see more details about Sprout changes without the need to direct people outside of sprout.

**Prioritization Process**

- [x] Confirm the issue is a feature to which we want to devote resources. 

- [ ] Write user story in `as a (role) I want (something) so that (benefit)` format. 

- [ ] Label story Large, Uncertain, Small. If the story is too large, convert the story to a milestone/epic. 

- [ ] Label story as an [active backlog](https://github.com/cssat/sprout-issues/projects/1) issue (i.e. an issue on which we will be actively working).

- [ ] Prioritize the story relative to other items in the [active backlog](https://github.com/cssat/sprout-issues/projects/1).

- [ ] Review progress/priorities in weekly collaboration meeting.

**Comment by joemienko** [comment]
This issue could be partially resolved by a social worker micro visitation app (i.e. SWs could see a log of report changes)

**Comment by subaykan** [comment]
Report History Download is available to basic users as well as org admins
