### ISSUE TITLE
Visit supervisors do not know when they are Adding Visit Reports to Resolved Referral

### ISSUE THREAD

**Issue by sarahyatsko** [cssat/sprout-issues#48]
**Is your feature request related to a problem? Please describe.**
Providers have noted that visit supervisors are too often mistakenly adding a visit report to a referral that has been resolved.  They recognize that this is sometimes necessary, but that the ability to enter a report on a resolved referral is also a problem because many times it is done when the visit supervisor should be entering the report in the open and active referral. 

**Describe the solution you'd like**
A warning message or dialogue box that would appear when the user click the ADD REPORT button to let the user know that they are about to enter a visit report on a resolved referral. 

**Describe alternatives you've considered**
Filter out resolved referrals from default view to reduce the likelihood that this happens. 

**Additional context**

**Prioritization Process**

- [ ] Confirm the issue is a feature to which we want to devote resources. 

- [ ] Write user story in `as a (role) I want (something) so that (benefit)` format. 

- [ ] Label story Large, Uncertain, Small. If the story is too large, convert the story to a milestone/epic. 

- [ ] Label story as an [active backlog](https://github.com/cssat/sprout-issues/projects/1) issue (i.e. an issue on which we will be actively working).

- [ ] Prioritize the story relative to other items in the [active backlog](https://github.com/cssat/sprout-issues/projects/1).

- [ ] Review progress/priorities in weekly collaboration meeting.

**Comment by joemienko** [comment]
@Deanna1968 - 
 
We believe that this issue has been resolved and is ready for acceptance. 
 
1. Please see the following user story
 
_As a Sprout user, I want to know when a referral has been resolved after I open it, so I don’t inadvertently enter a visit report on a resolved referral._  
 
2. Please confirm the following acceptance criteria for this story
**Given**: that a referral is resolved
**And**: the user has clicked on the referral from their queue and opened the referral
**When**: the user views the referral
**Then**: the user is informed that the referral has been resolved.

**Comment by Deanna1968** [comment]
HI Joe,

I am trying to get into Github.  I having trouble with my password.  But this is correct below.   Can you enter my comment into Github.

Sorry
Deanna

**Comment by Deanna1968** [comment]
The story is correct and accepted!  Please go forth and conquer!

**Comment by joemienko** [comment]
@cssatmcfunk  - This is ready for production

--> Need to check-in with the group about how to proceed in sequencing the push of accepted features to production.

**Comment by sarahyatsko** [comment]
@jessicamorris64 

Jessy, I'm wondering if this is what you are thinking about . . . 

A change approved by Deanna and deployed to Sprout in mid 2020 added an alert to provider users if the referral they were entering a visit report on was resolved. The ask was to simply alert providers, but not to prevent providers from entering reports on a resolved referral. There are no issues entered in GitHub asking that providers be preventing from entering a report post resolution.
