### ISSUE TITLE
Provider Missed Visits are showing in Billing Download

### ISSUE THREAD

**Issue by sarahyatsko** [cssat/sprout-issues#51]
**Describe the bug**
The current billing download includes data on all visits, missed and attended. A provider may bill for one hour of work for a visit where the child or parent No-Showed or cancelled within 24 hours of the visit. When a visit is cancelled, there is a field that asks who missed the visit. Visits missed by provider or child are not included in the total of missed visits for purposes of counting missed parent visits.  However, the billing download DOES include them, which means that providers could be billing (inadvertently) for visits cancelled within 24 hours or missed by the PROVIDER.  Presumably, providers should not be able to bill for visits that THEY missed. 

**To Reproduce**
Fill out a missed visit report, choose "provider" under "who missed visit" then download billing file. 

**Expected behavior**
Expected visits that provider missed to NOT be included on invoice.

**Comment by joemienko** [comment]
@jooreea will be writing an interim replacement extract for the billing download and @sarahyatsko will support invoicing for all non-FIN providers.  

Labeling this as do not fix and closing
