### ISSUE TITLE
Providers still show up in the registration dropdown after the provider's relationship with DCYF is terminated

### ISSUE THREAD

**Issue by joemienko** [cssat/sprout-issues#60]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Prioritization Process**

- [ ] Confirm the issue is a feature to which we want to devote resources. 

- [ ] Write user story in `as a (role) I want (something) so that (benefit)` format. 

- [ ] Label story Large, Uncertain, Small. If the story is too large, convert the story to a milestone/epic. 

- [ ] Label story as an [active backlog](https://github.com/cssat/sprout-issues/projects/1) issue (i.e. an issue on which we will be actively working).

- [ ] Prioritize the story relative to other items in the [active backlog](https://github.com/cssat/sprout-issues/projects/1).

- [ ] Review progress/priorities in weekly collaboration meeting.

**Comment by joemienko** [comment]
We now prefix orgs with "DEACTIVATED" in order to make clear that they are no longer available for registration.

**Comment by cdoran99** [comment]
Re-open. The quick fix is working well, but we need a full fledged solution to remove these providers rather then sorting them out of the way.
