### ISSUE TITLE
In the visit report list, User tasks are not clear due to Resume and View buttons being the Same Color

### ISSUE THREAD

**Issue by sarahyatsko** [cssat/sprout-issues#63]
**Is your feature request related to a problem? Please describe.**
When visit supervisors check the visit reports page, they scan the page for any reports they have not completed.  But since the VIEW and the RESUME buttons are the same color, they might miss a RESUME in a sea of VIEWs. 

**Describe the solution you'd like**
The RESUME button is a contrasting color, which helps the admin users find reports that need approval.  Similarly, if the RESUME button was another color it would help the visit supervisor quickly identify any unfinished reports. 

**Describe alternatives you've considered**
Status quo and a reminder in trainings 

**Additional context**

**Prioritization Process**

- [ ] Confirm the issue is a feature to which we want to devote resources. 

- [ ] Write user story in `as a (role) I want (something) so that (benefit)` format. 

- [ ] Label story Large, Uncertain, Small. If the story is too large, convert the story to a milestone/epic. 

- [ ] Label story as an [active backlog](https://github.com/cssat/sprout-issues/projects/1) issue (i.e. an issue on which we will be actively working).

- [ ] Prioritize the story relative to other items in the [active backlog](https://github.com/cssat/sprout-issues/projects/1).

- [ ] Review progress/priorities in weekly collaboration meeting.

**Comment by subaykan** [comment]
low pri, easy win

**Comment by gregorp** [comment]
User suggested in a ticket: https://oliver.zendesk.com/agent/tickets/19642

**Comment by keithligon** [comment]
This has been implemented. https://github.com/cssat/sprout/pull/150/commits/54d3b443dcff2e1077765bba77103635f5ec4fb3 
resolving.
