### ISSUE TITLE
Log Archiver Servers Need Cleanup, Monitoring

### ISSUE THREAD

**Issue by cssatmcfunk** [cssat/sprout-issues#64]
**Describe the bug**
We are at risk for outages in log archiving

**Expected behavior**
* Build new instances of the log archive servers to validate the existing setup instructions and to bring them up to date with newer technologies
* Set up log rotation to ensure disk space does not run out
* Set up monitoring around disk space
* Set up monitoring for actual log archive operations (check against S3)
* Clean up logging security group in AWS

**Comment by joemienko** [comment]
@yhtill @cssatmcfunk When this is complete, it would probably be good to write a brief post-mortum to make clear where we've had spotty log coverage
