### ISSUE TITLE
Incomplete List of Options for Who Missed Visit 

### ISSUE THREAD

**Issue by sarahyatsko** [cssat/sprout-issues#65]
**Is your feature request related to a problem? Please describe.**
The options under the OBSERVATIONS tab on a visit report for a missed visit include only Child, Parent, Foster Parent, Social Worker and Provider.

Providers have shared that they would like a "Custodial Parent" option and an "Other" option. 

If the child is living with bio mom and bio dad has a referral for visits, and bio mom prevents the visit from happening, the visit supervisor does not want to select "Parent" for who missed on the OBSERVATIONS page as this will count as a missed visit against dad. 

Also, there can be a reason why a parent misses a visit through no fault of their own.  Common example is prison visits. Visit supervisor brings child to the prison and there is a general lock down or some other reason visit can't happen.  Again, visit supervisor does not want to select "Parent" as they do not believe this should be counted as a strike against parent. 

**Describe the solution you'd like**
Add "Custodial Parent" and "Other" 

**Describe alternatives you've considered**
Train providers to select Child and write an explanation in the text field. 

**Additional context**

![Screen Shot 2020-01-29 at 10 04 46 AM](https://user-images.githubusercontent.com/49733235/73384353-f9f3b680-427f-11ea-8ce3-8bda43d2cdd1.png)

**Prioritization Process**

- [ ] Confirm the issue is a feature to which we want to devote resources. 

- [ ] Write user story in `as a (role) I want (something) so that (benefit)` format. 

- [ ] Label story Large, Uncertain, Small. If the story is too large, convert the story to a milestone/epic. 

- [ ] Label story as an [active backlog](https://github.com/cssat/sprout-issues/projects/1) issue (i.e. an issue on which we will be actively working).

- [ ] Prioritize the story relative to other items in the [active backlog](https://github.com/cssat/sprout-issues/projects/1).

- [ ] Review progress/priorities in weekly collaboration meeting.

**Comment by joemienko** [comment]
It may be worth thinking about how we could dynamically populate this dropdown with visit participants and foster parents. 

- Visit participants could come from Sprout. 
- Foster parents could come from FamLink

**Comment by joemienko** [comment]
@sarahyatsko Why do we need information from DCYF on this one?

**Comment by sarahyatsko** [comment]
@joemienko Put DCYF on here to be on the safe side - in case they needed to weigh on on who they think should be included as options for a missed visit.

**Comment by joemienko** [comment]
Some combination of the three of us need to decide what we want this to look like.

**Comment by joemienko** [comment]
@Deanna1968 , 

Do you have a specific list of individuals who are 1. At fault for a missed visit, and 2. What the reason for missing is?

**Comment by joemienko** [comment]
This will be addressed under #94
