### ISSUE TITLE
Sprout client is not saving data

### ISSUE THREAD

**Issue by sarahyatsko** [cssat/sprout-issues#66]
**Is your feature request related to a problem? Please describe.**
Several recent Sprout tickets and comments from users reaching out to me directly include frustration around  losing data they have entered. This includes things like mileage and parts of visit notes. Users have mentioned being in spotty internet range when data loss occurred. 

**Describe the solution you'd like**
An off line form for visit reports that can be uploaded to Sprout. 

**Describe alternatives you've considered**
I have encouraged visit supervisors to do what Region 1 has been doing - use Word or some other off-line word processing tool to record visit details and visit notes, and then to enter (some info like visit notes can be copied and pasted) in to Sprout once they are in strong wifi. 

**Additional context**

**Prioritization Process**

- [ ] Confirm the issue is a feature to which we want to devote resources. 

- [ ] Write user story in `as a (role) I want (something) so that (benefit)` format. 

- [ ] Label story Large, Uncertain, Small. If the story is too large, convert the story to a milestone/epic. 

- [ ] Label story as an [active backlog](https://github.com/cssat/sprout-issues/projects/1) issue (i.e. an issue on which we will be actively working).

- [ ] Prioritize the story relative to other items in the [active backlog](https://github.com/cssat/sprout-issues/projects/1).

- [ ] Review progress/priorities in weekly collaboration meeting.

**Comment by joemienko** [comment]
This is an umbrella issue - likely an EPIC. Much of the issues in the umbrella could be solved by transition to PWA.

**Comment by cdoran99** [comment]
@sarahyatsko Resolved with low connection message?
