### ISSUE TITLE
Visit coordinators cannot edit approved visit participants

### ISSUE THREAD

**Issue by joemienko** [cssat/sprout-issues#7]
As a visit coordinator, I should be able to add visit participants, so that I can modify this portion of the referral without creating a new visit plan

**Comment by joemienko** [comment]
This should be allowed by visit coordinators only. 
Unclear whether or not this should be allowed for NA role as well.

**Comment by joemienko** [comment]
Deanna said that she will talk with David and get back to us.

**Comment by sarahyatsko** [comment]
Note from David Sexton - FIN should not be able to add visit participants - so some discussion is needed to determine whether or not there's needs to be a VC role within DCYF to do this in Regions 1 and 2.

**Comment by sarahyatsko** [comment]
Also, a concern expressed by Jolene was included in an email from Jessy:

Jolene did have a comment about this, that made her a bit nervous. When she was a supervisor her staff would occasionally approve things she did not agree to, and she is a little worried about them telling VC’s it’s ok to add people without a supervisor’s knowledge. Just something to think about. But I also do not like the thought of having to create a new referral just for adding an other participant.

**Comment by joemienko** [comment]
Per @Deanna1968 guidance from last week, we no longer want this functionality. 

New participants require a new referral.
