### ISSUE TITLE
VCs cannot edit visit notes once the referral leaves their organization

### ISSUE THREAD

**Issue by joemienko** [cssat/sprout-issues#72]

**Comment by joemienko** [comment]
This is not an issue. 

Service admins can edit visit notes (not basic users). 

@yhtill suspects that this is an issue of the VC and the provider not having the same region

@sarahyatsko will confirm that this is the case in the UI

**Comment by joemienko** [comment]
Probably linked to #55 #50

**Comment by cdoran99** [comment]
This would be for the event when there are changes to the referral that doesn't warrant the creation of a new referral.

**Comment by subaykan** [comment]
Fixed as a result of recent permission changes
