### ISSUE TITLE
Organization famlinkId field is typically missing or invalid

### ISSUE THREAD

**Issue by joemienko** [cssat/sprout-issues#73]
**ISSUE**: We currently have no straight-forward way of mapping famlink PROVIDERS to Sprout ORGANIZATIONS. The `famlinkId` field within `organizations` in Sprout could meet this need, but the field has been abused over the years. 

DCYF would like to be able to easily link DCYF organizations to FamLink providers for reporting, etc. 

**IMMEDIATE TASK**: Someone with FamLink access _**and**_ `superadmin` status, or a FamLink user and a `superadmin` need to scrub the `famlinkId` field for all orgs contracted with DCYF. 

The end result should be a valid FamLink provider ID (DCYF to choose which field) for all orgs contracted with DCYF. 

**LONG TERM PROCESS CHANGE**: When new organizations are created in Sprout, DCYF needs to provide the creator with a valid FamLink provider ID.

**Comment by joemienko** [comment]
Some combination of the assigned crew needs to come up with a plan to enter FamLink provider IDs into sprout as noted above.

**Comment by joemienko** [comment]
CSSAT to provide Jolene with a list of provider names, locations, and other relevant information 

Jolene to scrub that against Famlink to get FamLink Provider IDs

CSSAT to enter Jolene's list into Sprout

**Comment by joemienko** [comment]
This is 95% complete. @sarahyatsko to finish later today...

We still need a policy in place for when new organizations are created in Sprout, DCYF needs to provide the creator with a valid FamLink provider ID.

@Deanna1968 @jessicamorris64, CSSAT is still responsible for creating all orgs. Who is the DCYF point of contact for provider IDs?

**Comment by joemienko** [comment]
@sarahyatsko , just doing backlog grooming. 

Did we ever finish entry here?

@Deanna1968 & @jessicamorris64 CSSAT is still responsible for creating all orgs. Who is the DCYF point of contact for provider IDs?

**Comment by jessicamorris64** [comment]
I spoke with Jolene about this and she reminded me that on February 26th she sent you a list of all the provider IDs for Family Time providers. You guys sent her a list first of all providers and she went line by line looking each of them up, as you know some of them do not have the same business name. Deanna and our contracts staff will have to work on any updates to where (regions/counties) those contractors are able to service.
[Comparison of contractor list - contracts vs Sprout Feb-2020.xlsx](https://github.com/cssat/sprout-issues/files/4880325/Comparison.of.contractor.list.-.contracts.vs.Sprout.Feb-2020.xlsx)

**Comment by joemienko** [comment]
@sarahyatsko has a process that is now handling this manually (we request the org id on creation of a new organization)

**Comment by jessicamorris64** [comment]
i think manually is fine as long as this step isn't missed when adding providers
