### ISSUE TITLE
We are paying Aptible for resources allocated beyond our base

### ISSUE THREAD

**Issue by yhtill** [cssat/sprout-issues#79]
For the period of Dec 17 - Jan 17, we incurred $455.32 in charges for resources utilized beyond our base allocation.  Since then, we have added more resources.

We could potentially cut these costs by identifying and reducing un- and under-utilized resources.

**Comment by joemienko** [comment]
@yhtill  - between the two of us, I fear that we have already expended the potential overspend in state resources in the time that has taken to think about this. 

I am closing this, but tagging you here so you'll be notified. Feel free to reopen this if you'd like.

**Comment by joemienko** [comment]
From Matt in Slack

> That was an "issue as a problem" for a range of cleanup that has been steadily growing, and really encompasses much more than cost.

Reopening to discuss how we want to triage the cleanup of aptible moving forward

**Comment by cssatmcfunk** [comment]
This falls into basically two buckets:

- General cleanup of old containers and endpoints that are effectively unnecessary

- Finalizing the switchover to sprout from oliver via setting up redirects and then discontinuing the oliver endpoints
