### ISSUE TITLE
Need to enable MFA for all users

### ISSUE THREAD

**Issue by joemienko** [cssat/sprout-issues#8]
As a sprout user, I should be required to enter two forms of authentication, so that sprout fully verify the legitimacy of all transactions

**Comment by joemienko** [comment]
This is something that we will be delaying until after substantial's SAW prototype

**Comment by joemienko** [comment]
Sorry for the delay in updating this issue. 

@yhtill has been back to work on this for the last couple of weeks, although he continues to context shift back to the CANS as bugs crop up there...

As of today (10/15) we have 

1. Built a functioning prototype that uses AWS SAML as a stand-in for SAW. 
2. Established access to the test/staging environment for SAW. 
3. Been granted a copy of the SAW IdP metadata template and guidelines for formulating SAML requests. 
4. Submitted an overview of our proposed setup to the SAW team. We are waiting for a response (they indicated they would be back in touch with us by 10/18). 

Once we hear back from the SAW team, we will work on transitioning our prototype from AWS to the SAW test/staging service. Ideally, we will have this work complete and ready to demo to the team by the **end of October**. However, this target may need to be revised depending on how much revision the SAW team requests.

Once we get the registration and authentication flow approved by the business team, we will need to come up with a plan to 

1. notify users of the change, 
2. train users on the change,
3. determine how many "test" instances of SAW authentication we want across our environments, and 
4. possibly request a waiver to allow DCYF users to access outside of AD/SSO. 

It would be good is we could solidify a plan for the above by the **end of November**. 

The current goal is to have integration complete and **all users accessing legacy sprout via SAW by EOY**.

**Comment by subaykan** [comment]
replaced with SAW
