### ISSUE TITLE
Ability to Add a Second Visit Supervisors on a Visit Report is Confusing

### ISSUE THREAD

**Issue by sarahyatsko** [cssat/sprout-issues#80]
**Is your feature request related to a problem? Please describe.**
Visit supervisors are frequently misusing the Add Visit Supervisor button on the visit report. 

**Describe the solution you'd like**
Eliminate the button

**Describe alternatives you've considered**

I will ask FIN if this button is useful. 

I am trying to think of a scenario where a second visit supervisor is needed. If there are two visit supervisors, they should be filling out two separate visit reports - so they would not need to add a second name to one report. When there are two visit supervisors on one report, it creates confusion over which one needs to be compensated. The report already allows for a driver to be different from the supervisor, which makes sense. 

**Additional context**

**Prioritization Process**

- [ ] Confirm the issue is a feature to which we want to devote resources. 

- [ ] Write user story in `as a (role) I want (something) so that (benefit)` format. 

- [ ] Label story Large, Uncertain, Small. If the story is too large, convert the story to a milestone/epic. 

- [ ] Label story as an [active backlog](https://github.com/cssat/sprout-issues/projects/1) issue (i.e. an issue on which we will be actively working).

- [ ] Prioritize the story relative to other items in the [active backlog](https://github.com/cssat/sprout-issues/projects/1).

- [ ] Review progress/priorities in weekly collaboration meeting.

**Comment by joemienko** [comment]
@Deanna1968  - Do we want to support multiple visit supervisors on the same visit (particularly, from an invoicing perspective)?

**Comment by joemienko** [comment]
We need to identify the "primary" visit supervisor on a visit report

We need to follow-up with providers to determine the best design approach.

**Comment by joemienko** [comment]
Will be addressed under #93 93
