### ISSUE TITLE
create a field to display Trial Return Home on the UI under child info section

### ISSUE THREAD

**Issue by jessicamorris64** [cssat/sprout-issues#83]
create a field to display Trial Return Home on the UI under child info section. this just needs to be a display fields that only shows what is sent from FamLink. this is not editable by anyone and will be updated in the nightly batch.
this is a priority as providers need to know where to find the child for pick-up and Drop-off. they have been rejecting referral because they don't know where to find the child.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Prioritization Process**

- [ ] Confirm the issue is a feature to which we want to devote resources. 

- [ ] Write user story in `as a (role) I want (something) so that (benefit)` format. 

- [ ] Label story Large, Uncertain, Small. If the story is too large, convert the story to a milestone/epic. 

- [ ] Label story as an [active backlog](https://github.com/cssat/sprout-issues/projects/1) issue (i.e. an issue on which we will be actively working).

- [ ] Prioritize the story relative to other items in the [active backlog](https://github.com/cssat/sprout-issues/projects/1).

- [ ] Review progress/priorities in weekly collaboration meeting.

**Comment by joemienko** [comment]
-- Confirmed that this is on the XML coming from FamLink presently.

**Comment by joemienko** [comment]
Addressed under #41
