### ISSUE TITLE
No Way to Filter Referral List by Visit Coordinator

### ISSUE THREAD

**Issue by sarahyatsko** [cssat/sprout-issues#86]
**Is your feature request related to a problem? Please describe.**
Visit Coordinators need to be able to filter their referral list for referrals assigned to them. This is a problem because filtering by their office will not show any referrals that has come to their region from another region. But if they assign themselves as the VC on all new referrals, then they can search for themselves and a full list of all the referrals they need to worry about would result.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Prioritization Process**

- [ ] Confirm the issue is a feature to which we want to devote resources. 

- [ ] Write user story in `as a (role) I want (something) so that (benefit)` format. 

- [ ] Label story Large, Uncertain, Small. If the story is too large, convert the story to a milestone/epic. 

- [ ] Label story as an [active backlog](https://github.com/cssat/sprout-issues/projects/1) issue (i.e. an issue on which we will be actively working).

- [ ] Prioritize the story relative to other items in the [active backlog](https://github.com/cssat/sprout-issues/projects/1).

- [ ] Review progress/priorities in weekly collaboration meeting.

**Comment by joemienko** [comment]
@yhtill in your referral list project, are you including Visit Coordinator assignments (i.e. assignments via `resourceSpecialistId`) in the assignment filter that you had demoed? 

If so, it seems like this is another issue that should get assigned to you and lumped into that larger set of features.

**Comment by joemienko** [comment]
@yhtill in your referral list project, are you including Visit Coordinator assignments (i.e. assignments via `resourceSpecialistId`) in the assignment filter that you had demoed? 

If so, it seems like this is another issue that should get assigned to you and lumped into that larger set of features.

**Comment by joemienko** [comment]
If visit coordinators added themselves to the referral, they can search for themselves, under the system as designed.

**Comment by jessicamorris64** [comment]
This is in current production or with the new filtering capabilities that were previously worked on?
