### ISSUE TITLE
We cannot distinguish between CPA and non-CPA orgs in Sprout

### ISSUE THREAD

**Issue by joemienko** [cssat/sprout-issues#88]

**Comment by joemienko** [comment]
@Deanna1968 , 

Can you clarify the long-term plan for CPAs WRT family time contracts?

Our understanding is that you are working everyone toward the "Amara" model - a model in which CPAs will be allowed to supervise visits, but they will be required to have a regular Family Time contract in order to supervise visits. Under that model, however, they will not be restricted to supervising visits for kids in their care. 

IOW - CPAs will not be any different than other providers in Sprout.

**Comment by Deanna1968** [comment]
Hi 

That is correct!  CPAs will not be any different than other providers in Sprout as long as they have a family time contract!

I am doing good here! of course I have a little blue girl birdy with the name Jessi helping me!!

**Comment by joemienko** [comment]
@Deanna1968 Killer - Thanks!

I am going to close this as wont fix then.
