### ISSUE TITLE
We do not have guidance to all tribes regarding the use of Sprout

### ISSUE THREAD

**Issue by joemienko** [cssat/sprout-issues#89]
Deanna will communicate to Bob Smith

Jolene & Shannon has already made this communication to several tribes

All of R6 has been invited
All of R5 has been invited

**Comment by joemienko** [comment]
@Deanna1968, Has this happened?

IOW, Can we consider this done?

**Comment by Deanna1968** [comment]
HI Joe, 

I am thinking we can consider this done. go ahead and close!!
