### ISSUE TITLE
Visit supervisors can complete a visit report without all information

### ISSUE THREAD

**Issue by joemienko** [cssat/sprout-issues#93]

**Comment by joemienko** [comment]
There is a desire from provider users to prevent the submission of visit reports for approval without all required information.

**Comment by joemienko** [comment]
We need to consult with providers on the desired behavior.

**Comment by joemienko** [comment]
@Deanna1968  - The only obvious field on visit reports that is not required is a visit supervisor. This may be difficult to implement. Is this a requirement?

Are there other required fields (that are not already required)?

**Comment by Deanna1968** [comment]
I am not clear on this one.  can you talk about it when I jump on the call today at 230? thanks

**Comment by joemienko** [comment]
@sarahyatsko has agreed to close this issue, and split it into 1-2 separate issues related to VC ability to edit/delete referrals

**Comment by joemienko** [comment]
Deanna agreed that we would want to require the entry of a visit supervisor.

**Comment by joemienko** [comment]
The required information makes this a duplicate of #80
