### ISSUE TITLE
Visit Coordinators (Region Admins) are Unable to View Visit Reports outside their Region

### ISSUE THREAD

**Issue by sarahyatsko** [cssat/sprout-issues#96]
**Describe the bug**
When a Region Admin in Sprout opens a referral and attempts to view a visit report completed by an organization from a different Region in Sprout, the Region Admin gets a "404" error message

**To Reproduce**
1. Log in as a VC/Region Admin
2. Open a referral that is in the vault of an organization in a DIFFERENT region from the VC/Region Admin's
3. Click on Report
4. See 404 error

**Expected behavior**
Expect to see the reports

**Additional context**
Per Marshal : 
The fix, as it seems to me, would be to create a new rule set that only applies to view visit report that would take into consideration whether the user belonged to a routing org and whether that org had a contract with the org on the report

**Comment by joemienko** [comment]
This is a dup of #76
