### ISSUE TITLE
Visit Report visit types do not allow for categorizing visits according to their "virtual" nature

### ISSUE THREAD

**Issue by joemienko** [cssat/sprout-issues#97]
DCYF wants more visit type categories for the Visit Type dropdown in the visit reports (attended and missed). 

The attended visit report is as follows:

![Screen Shot 2020-03-31 at 10 00 02 AM](https://user-images.githubusercontent.com/37134346/78054814-76b21800-7337-11ea-97c8-e2702b792458.png)

The total set of visit categories should include: 

-- Monitored
-- Supported Visitation
-- Supervised
-- Transport Only
-- Virtual - Monitored
-- Virtual - Supported Visitation
-- Virtual - Supervised
-- Virtual - Transport Only

**Comment by joemienko** [comment]
@Deanna1968 , @jessicamorris64 , at our triage meeting this morning. 

@yhtill suggested it would be preferable to simply add a "Virtual" flag to the form instead of adding to the dropdown. 

Any objection to this?

**Comment by jessicamorris64** [comment]
I don’t object to this, but it’s up to Deanna.

**Comment by Deanna1968** [comment]
sounds good,  clearly it will provide what Ross is looking for as in data, correct?

**Comment by Deanna1968** [comment]
I don’t object.

**Comment by yhtill** [comment]
Here's what the flag looks like:
![image](https://user-images.githubusercontent.com/20548990/78067379-7c195d80-734b-11ea-905e-d3a4187d8e8c.png)
