### ISSUE TITLE
Missed visit counter counts against parent when reason is tech issues

### ISSUE THREAD

**Issue by sarahyatsko** [cssat/sprout-issues#99]
**Is your feature request related to a problem? Please describe.**
When a remote visit does not happen because parent does not have a device or internet or the app does not work, the provider lists the parent as the party that caused the missed visit  on the Missed Visit report and then chooses the new item of technical issues in the reason drop down.  However, providers are then surprised to see that this missed visit is counting against the parent. 

**Describe the solution you'd like**
Add technology to the list of parties that caused the missed visit
OR
Do not count this as a missed visit for the parent is the reason is technology issues. 

**Describe alternatives you've considered**
DCYF has instructed the providers to list the provider as the party that caused the missed visit and that it will not be counted against them, but all the providers I have spoken or emailed with about this (6 or so) are leery of this suggestion and fear it will reflect poorly on them in the data. 

**Prioritization Process**

- [ ] Confirm the issue is a feature to which we want to devote resources. 

- [ ] Write user story in `as a (role) I want (something) so that (benefit)` format. 

- [ ] Label story Large, Uncertain, Small. If the story is too large, convert the story to a milestone/epic. 

- [ ] Label story as an [active backlog](https://github.com/cssat/sprout-issues/projects/1) issue (i.e. an issue on which we will be actively working).

- [ ] Prioritize the story relative to other items in the [active backlog](https://github.com/cssat/sprout-issues/projects/1).

- [ ] Review progress/priorities in weekly collaboration meeting.

**Comment by joemienko** [comment]
Need a decision from DCYF about who (if anyone) should be at fault for missed visits due to tech issues. 
1. Need to determine this for missed visits during COVID-19 AND
2. Need to determine this for the long term (beyond COVID-19).

**Comment by joemienko** [comment]
Per @Deanna1968, if the miss is a confirmed technical issue (vs a no-call no-show), it does not count against the parent.

**Comment by joemienko** [comment]
Some advice to providers is to always place the "fault" to the provider (which should solve this problem). 

This advice has not been consistent though (different providers have been getting different messages)

@Deanna1968  - do we have consistent guidance that has been communicated to providers?

**Comment by joemienko** [comment]
Last meeting we decided that @Deanna1968  was going to consult on the business side to determine strategy here - provide a better categorization in sprout or train providers to always place fault with the provider. 

@Deanna1968  - any further thoughts on this?

**Comment by subaykan** [comment]
Caitlin will re-explore
